### ISSUE TITLE
Should SCREAM have release mode nightlies?

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#539] opened 2020-09-01 18:01 UTC
We cannot (in general) do BFB testing cxx-vs-f90 in debug mode, due to potentially different optimizations/rounding (especially with GPU builds). However, we could still check against baselines.

Among the benefits, the most important I can see is that we could catch build/runtime errors that do not happen in debug mode (e.g., some optimizations that are unsafe due to algorithm/design details).

Pinging @jgfouca as the testing master.

**Comment by jgfouca** [comment] 2020-09-04 18:10
Yes, we should. We have plenty of nightly testing resources available.

**Comment by bartgol** [comment] 2020-09-04 19:13
Issue #525 is another reason why we should not limit our testing to debug mode.

Note: "testing" is meant in a sense broader than just "run our tests"; testing the build system itself is important. It is ok to disable some BFB tests if debug is not on.

**Comment by PeterCaldwell** [comment] 2020-12-10 23:49
@bartgol - I think we have been doing baseline testing for a while now on weaver(?). Can we close this issue?

**Comment by bartgol** [comment] 2020-12-10 23:57
Weaver still does only debug mode. This issue wonders whether we should test also our production code (if not for correctness, at least for "not crashing").

**Comment by PeterCaldwell** [comment] 2020-12-11 17:28
@bartgol - Ok, testing that we can build and run and run in production mode seems like a good idea. And I guess we might as well do production baselines while we're at it. As long as we have the computer time and generating baselines for debug and production mode isn't too onerous.

**Comment by bartgol** [comment] 2020-12-11 18:00
Right, baseline tests can of course be run also in release mode. We just can't run bfb tests (though for some we could, with a proper tolerance).

**Comment by PeterCaldwell** [comment] 2020-12-11 18:17
Ok. To disambiguate, we **can** test that master is BFB with older versions of master because E3SM requires BFB reproducibility. This is what you mean by baseline testing. But F90 and C++ implementations won't be BFB, which is what you mean by bfb tests in your comment above. And this issue is about running our unit tests, not running full E3SM builds.

In this context, my feeling is that more testing is always better but this sounds like a lot of work to implement and keep running. I'm not sure it's worth it?

**Comment by bartgol** [comment] 2020-12-11 18:22
Adding one more build to the AT/nightlies is a matter of 1h of work. I think this is still worth it, but perhaps it can wait till we have full atm runs with the AD (even in standalone mode). Then we can add some netcdf output test against baselines.

I would say, let's leave this issue open, and get back to it in ~6 months.

**Comment by jgfouca** [comment] 2021-02-26 20:56
Fixed by #891

**Closed** 2021-03-01 16:40 UTC
Labels: priority:wishlist, testing
