### ISSUE TITLE
Error with ERS test ERS_P8x1_Ln9.ne30_ne30.F2010-SCREAMv1.perlmutter_gnugpu

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1661] opened 2022-05-21 16:46 UTC
The test in cdash `ERS_Ln9.ne30_ne30.F2010-SCREAMv1.perlmutter_gnugpu` fails as there is not enough memory on 1 node. Where I think I was able to run ne30 on 1 node before (after SPA memory improvements), but will have to look at that later. When I try to run on 2 nodes, ie `ERS_P8x1_Ln9.ne30_ne30.F2010-SCREAMv1.perlmutter_gnugpu`, I get this error:

```
0: [EAMXX] create_grids ... done!
0: [EAMXX] create_fields ...
0: [EAMXX] create_fields ... done!
0: [EAMXX] initialize_fields ...
0:   [EAMXX] Run  start time stamp: 0001-01-01.023000
0:   [EAMXX] Case start time stamp: 0001-01-01.000000
0:   [EAMXX] restart_model ...
1: terminate called after throwing an instance of 'std::logic_error'
1:   what():  /pscratch/sd/n/ndk/wacmy/s21-may19/components/scream/src/control/atmosphere_driver.cpp:540: FAIL:
1: found
1: Error! Output restart requested, but no model restart file found in 'rpointer.atm'.
1:    restart file casename: ERS_P8x1_Ln9.ne30_ne30.F2010-SCREAMv1.perlmutter_gnugpu.20220521_083150_gyas9n
1:    restart file suffix: 0001-01-01.023000.r.nc
1:    rpointer content:
1: ERS_P8x1_Ln9.ne30_ne30.F2010-SCREAMv1.perlmutter_gnugpu.20220521_083150_gyas9n.INSTANT.Steps_x5.0001-01-01.023000.r.nc
2: terminate called after throwing an instance of 'std::logic_error'
2:   what():  /pscratch/sd/n/ndk/wacmy/s21-may19/components/scream/src/control/atmosphere_driver.cpp:540: FAIL:
2: found
2: Error! Output restart requested, but no model restart file found in 'rpointer.atm'.
2:    restart file casename: ERS_P8x1_Ln9.ne30_ne30.F2010-SCREAMv1.perlmutter_gnugpu.20220521_083150_gyas9n
2:    restart file suffix: 0001-01-01.023000.r.nc
2:    rpointer content:
2: ERS_P8x1_Ln9.ne30_ne30.F2010-SCREAMv1.perlmutter_gnugpu.20220521_083150_gyas9n.INSTANT.Steps_x5.0001-01-01.023000.r.nc
2:

/pscratch/sd/n/ndk/e3sm_scratch/perlmutter/s21-may19/ERS_P8x1_Ln9.ne30_ne30.F2010-SCREAMv1.perlmutter_gnugpu.20220521_083150_gyas9n
```

**Comment by PeterCaldwell** [comment] 2022-05-21 22:49
My understanding is that https://github.com/E3SM-Project/scream/pull/1619 - merged at 1pm yesterday - had some fixes for restarts. It could be that grabbing a newer repo version would fix this?

**Comment by ndkeen** [comment] 2022-05-22 16:59
ok

**Comment by ambrad** [comment] 2022-07-07 23:53
I'm going to reopen this because the pm-gpu nightlies are reporting this error.

**Comment by PeterCaldwell** [comment] 2022-07-08 00:04
I have a vague recollection that we recently changed our default file names to not shout INSTANT at us. It looks like restarts didn't get that memo? @AaronDonahue - I think you changed the file names - does this error make sense to you? Not asking you to solve it necessarily because you have other tasks to do before vacation...

**Comment by ambrad** [comment] 2022-07-08 00:29
@AaronDonahue for clarity the most up-to-date error message is this:
```
1: terminate called after throwing an instance of 'std::logic_error'
1:   what():  /global/u2/e/e3smtest/jenkins/workspace/SCREAM_NightlyTests_Perlmutter_Cime/ACME/components/scream/src/share/io/scream_io_utils.cpp:64: FAIL:
1: found
1: Error! Restart requested, but no restart file found in 'rpointer.atm'.
1:    restart case name: ERS_Ln22.ne30_ne30.F2010-SCREAMv1.pm-gpu_gnugpu.JMasterScream_v1_medres20220706_193701.scream
1:    restart file type: model restart
1:    rpointer content:
1: ./ERS_Ln22.ne30_ne30.F2010-SCREAMv1.pm-gpu_gnugpu.JMasterScream_v1_medres20220706_193701.scream.r.0001-01-01-21600.nc
```
So the part about INSTANT isn't relevant.

**Comment by ambrad** [comment] 2022-07-27 23:32
I looked into this because I want to get some pg2 ERS/P tests running on PM. I discovered that the problem is the broadcast of the boolean here: https://github.com/E3SM-Project/scream/blob/4ac726cf72906670206104611afdda7af2575e5f/components/scream/src/share/io/scream_io_utils.cpp#L55

My fix follows:
```c++
  int ifound = int(found);
  comm.broadcast(&ifound,1,0);
  found = bool(ifound);
```
This gets the ERS/P tests passing.

**Closed** 2022-07-29 21:25 UTC
Labels: SCREAMv1
