### ISSUE TITLE
gather-all-data fails on branch on quartz.llnl.gov

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#567] opened 2020-09-10 20:48 UTC
When I 
```
git clone https://github.com/E3SM-Project/scream.git
git submodule update --init --recursive
git checkout PeterCaldwell/fix_rain_evap2
${CODE_ROOT}/components/scream/scripts/gather-all-data '${CODE_ROOT}/components/scream/scripts/test-all-scream $(which mpicxx) --integration -m quartz' -l -m quartz
```
I get 
```
###############################################################################
Generating baselines for ref origin/master
###############################################################################
Warning: repo is not clean: /bin/sh: ml: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_ml'
Warning: repo is not clean: /bin/sh: ml: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_ml'
ERROR: If we need to change HEAD, then the repo must be clean before running
```
I don't understand how my repo isn't clean since I literally just cloned it. If I redo the above steps but don't switch from the master branch, tests pass but I still get "/bin/sh: ml: line 1: syntax error: unexpected end of file" complaints. So... @AaronDonahue - do you get the same fail when you try other branches w/ gather all data? Anyone - do you get the same error on other machines when you try to gather_all_data on a branch? I suspect the issue may be related to interaction between our testing infrastructure and our new usage of submodules. @bartgol - do you have any ideas about what might be going on?

We should probably fix this, but I don't see it being urgent.

**Comment by PeterCaldwell** [comment] 2020-09-10 20:49
Oh, I should also mention that I reproduced the issue on lassen.llnl.gov. Perhaps not surprising since lassen and quartz have very similar environments.

**Comment by AaronDonahue** [comment] 2020-09-10 21:38
@PeterCaldwell I am able to reproduce this issue following your commands.  I checked on lassen with the recently merged branch from Luca, bartgol/grid_upgrades, and also had the same failure.  Which seems to indicate it is not an issue with your branch.

As a sanity check I ran the testing command using `master` on quartz and that appears to be working.  So it does have something to do with running on a branch.

**Comment by AaronDonahue** [comment] 2020-09-10 21:43
If you use `-b HEAD` it does start to build though.  This is not ideal since the baselines would then match your branch and you won't be able to detect a change from master.

**Comment by AaronDonahue** [comment] 2020-09-10 21:45
"I don't understand how my repo isn't clean since I literally just cloned it"

Is it possible that the

**Comment by bartgol** [comment] 2020-09-11 01:50
Not sure if it has an impact, but the integration flag for test-all-scream is `--integration-test` or `-i`, while you reported `--integration` (maybe it was just a typo when you wrote down the issue).

Another thing you could try is to run just test-all-scream (gotta run it from the `component/scream` folder, IIRC), and see if you get the same error. It might crap out because you are not on a compute node, and maybe some modules or the architecture is different on the login node, but we would be able to see if you still get a warning regarding the non clean tree.

Also, at the cost of asking the obvious:
1) you did cd into `scream` after cloning right? I mean, the git commands should error out if you weren't, but just to be sure.
2) your CODE_ROOT variable points to the freshly cloned copy, right?

**Comment by PeterCaldwell** [comment] 2020-09-23 17:23
I think when you check out a new branch, it automatically switches to the appropriate hashes for each submodule. Otherwise git checkout would be a total disaster... so I don't think the order of submodule update is the problem. In fact, I tried checking out a new repo, switching to a branch, git submodule update-ing, then gather-all-data-ing... and still got this error. I used a different branch for this experiment from the one spawning this issue, further confirming that this is a general problem on LC machines rather than a bug in my particular branch. 

I suspect there's something wrong with the bash environment on LC machines that our testing machinery is tripping over.

**Comment by bartgol** [comment] 2020-09-23 18:12
Ok, I'm not sure what's going on with LC machines then.

But to be clear, `git checkout` does *not* update submodules. You can, of course, configure git to automatically do that (either changing `checkout` defaults or by defining an alias that recurse submodules), but it is not the default git behavior.

**Comment by bartgol** [comment] 2020-09-23 18:15
Ah, I know what's happening. It's not your fault. In our testing scripts we manipulate the env, but I found out some env vars were problematic. On Fedora, we have the `BASH_FUNC_module` that broke the script, so I put a special handling for that. I assume on your system the same var is called `BASH_FUNC_ml`.

Let me try to put a fix in a branch, so you can try it.

**Closed** 2020-09-23 19:39 UTC
Labels: infrastructure, testing
