### ISSUE TITLE
E3SM cime_config machine-file-set CXXFLAGS gets nullified somewhere.

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#1889] opened 2022-08-23 23:46 UTC
I can work around the following issue but don't have a general solution for it. I'm mentioning it here so that infrastructure folks can think about it. In E3SM's cime_config, it's common to see `string(APPEND CXXFLAGS "...")` (where ... represents some text). But something in EKAT, Kokkos, or SCREAM's CMake code is nullifying those appends. I find that if I put the modification to CXXFLAGS in scream/cmake machine files, those stay, so that's my workaround for now.

**Comment by oksanaguba** [comment] 2022-08-24 00:04
Jim or Luca will know better, but I think it is by design, and we are supposed to use scream/cmake/machine files for scream flags.

**Comment by ambrad** [comment] 2022-08-24 00:06
True, but I believe we don't want to prevent the general user from, say, adding extra debug flags in the standard E3SM way.

**Comment by oksanaguba** [comment] 2022-08-24 00:11
Then i have a related question -- in scream/cmake files, we can only set CXX_FLAGS. We cannot (i think) do ADD_... variables, which I think are better than varuables that seem to "reset" flags.

**Comment by bartgol** [comment] 2022-08-24 02:23
Re: mach files. The mach files are used in two different ways in standalone vs CIME mode. CIME simply "includes" the mach file inside the cmake stack, while standalone scream "preloads" them as cache file (via `-c $mach_file`).

Among others, one big difference is that cache files only supports setting cache variables (so no `set(MY_VAR,MY_VAL)` or if statements), while if the file is included, one can do any sorts of cmake snippet.

I think at some point we want to change the standalone way, to use mach files as "included" files, so that we can do things in the same way. This might require to change also the way ekat is implemented (not to mention the fact that preloading a cache file is probably the most common approach for cmake projects, but that's more subjective).

**Comment by bartgol** [comment] 2022-08-24 02:35
The issue you opened/closed in Ekat might be relevant. I think that macro is the only place where we use the variable CXXFLAGS, withouth prepending any string. The macro is called from inside another macro, which is itself called in both ekat's and scream's main CMakeLists.txt. Macros do _not_ open a new scope (unlike macros), so that usage of CXXFLAGS _will_ alter the value of CXXFLAGS at the call site.

**Closed** 2023-01-04 20:35 UTC
