### ISSUE TITLE
Support for REST_OPTION=end

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#2304] opened 2023-04-25 19:37 UTC
In CIME there is an option for restarts called "end" that we do not support in EAMxx.  It is the default option for E3SM and a nice option overall, meaning that we will just write a restart when the current simulation ends.

This task is to add support for this option.

**Comment by bartgol** [comment] 2024-05-28 17:50
This seems to be a duplicate of #793

**Closed by bartgol** 2024-05-28 17:50 UTC
Labels: enhancement, help wanted, I/O, priority:medium
