### ISSUE TITLE
Non filled values in variables interpolated to a fixed pressure level

### ISSUE THREAD

**Issue by elynnwu** [E3SM-Project/scream#2585] opened 2023-10-25 21:18 UTC
I noticed variables such as `T_mid_at_850hPa` has values of `2.8356864e+33`, when the fill value for this variable is `3.4028236e+33`. In fact, for this specific case, there're multiple values in the 1e32 to 1e33 order that are not filled values. It is likely that the vertical interpolation isn't working properly with the at level diagnostics.

**Comment by AaronDonahue** [comment] 2023-10-25 21:24
I think the issue might be here: https://github.com/E3SM-Project/scream/blob/master/components/eamxx/src/diagnostics/field_at_height.cpp#L148

We are doing the interpolation locally without considering the existence of "fill value".  The solution should hopefully be as simple as checking for fill value and adjusting this interpolation line accordingly.

**Comment by PeterCaldwell** [comment] 2023-10-25 21:26
Does this mean that some of our Cess output is corrupted?

**Comment by AaronDonahue** [comment] 2023-10-25 21:32
nevermind, I think its actually here: 
```
  m_mask_val = m_params.get<double>("mask_value",Real(std::numeric_limits<float>::max()/10.0));
```

> Does this mean that some of our Cess output is corrupted?
If I'm right, then no, just that the fill value for any pressure slices is different than the fill value we use elsewhere.  So not corrupt, just annoying to post-process

**Comment by AaronDonahue** [comment] 2023-10-25 21:39
confirmed that this mask value doesn't match the default used in our output.  they should differ by a factor of 2.  @elynnwu  can you confirm that what you are seeing is half the size of the default fill value we are used to?

**Comment by PeterCaldwell** [comment] 2023-10-25 22:37
Oh phew.

**Comment by elynnwu** [comment] 2023-10-25 23:06
But is there a reason there are multiple unique large values?
Here're the values from a baseline ne30 run, no nudging or mlcorrection:

```
f = xr.open_mfdataset("output.scream.AVERAGE.nhours_x3.2011-*.nc")
np.unique(np.sort(f.T_mid_at_850hPa.isel(time=10)))[-10:]
array([3.07124725e+02, 3.07140991e+02, 3.07231445e+02, 3.07304169e+02,
       5.67137277e+32, 1.13427455e+33, 1.70141179e+33, 2.26854911e+33,
       2.83568642e+33,            nan], dtype=float32)
```
There're 5 unique values between 1e32 to 2.8e33 that are not the filled value (`3.402824e+33`)

**Comment by bartgol** [comment] 2023-10-25 23:07
@elynnwu that may come from the time averaging. Have you tried to check instantaneous output?

**Comment by elynnwu** [comment] 2023-10-25 23:15
Oh good point, this is time averaged.

**Comment by bartgol** [comment] 2023-11-15 23:29
@elynnwu did you have a chance to verify whether this was due to time averaging?

**Comment by elynnwu** [comment] 2023-11-15 23:57
Yes, the non unique large values are due to time averaging.

**Comment by bartgol** [comment] 2023-11-16 00:21
Ok, so the issue is now to find a way to not average fill values...

**Comment by bartgol** [comment] 2024-12-06 17:47
@AaronDonahue I think this has been fixed long time ago, right? Closing.

**Closed by bartgol** 2024-12-06 17:47 UTC
Labels: bug, diagnostic
