### ISSUE TITLE
Make C++ version of physgrid remap

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#855] opened 2021-01-07 20:52 UTC

**Comment by bartgol** [comment] 2021-09-23 04:22
Duplicate of #574

**Comment by bartgol** [comment] 2021-09-23 04:23
Reopening, and closing the old issue, since this seems to have been followed more.

**Comment by ambrad** [comment] 2023-01-05 01:14
Done summer 2021.

**Closed by ambrad** 2023-01-05 01:14 UTC
Labels: homme, priority:low
