### ISSUE TITLE
[AD] Get rid of remaining F90 in SCREAMv1 I/O interface

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#823] opened 2020-12-14 15:55 UTC
Our current I/O interface has a legacy fortran layer in its communication between Scorpio and the AD. This was done to speed up the implementation process but should be converted to C++ for simplicity/code clarity.

**Comment by bartgol** [comment] 2021-08-19 22:39
This seems like a duplicate of #792

**Closed by bartgol** 2021-08-19 22:39 UTC
Labels: code quality, Atmosphere Driver, priority:wishlist
