### ISSUE TITLE
ne256 SCREAMv1 seg fault during initialization

### ISSUE THREAD

**Issue by bogensch** [E3SM-Project/scream#1699] opened 2022-05-31 15:42 UTC
SCREAM ne256 v1 runs are seg faulting during initialization with "array index out of bounds" in "Unknown" routine, line, and source. 

Details
Branch used: brhillman/eam/add-ne256np4
machine: Cori-knl
number of procs: 3072

run directory on NERSC:
/global/cscratch1/sd/bogensch/e3sm_scratch/cori-knl/F2010-SCREAMv1.ne256np4_oRRS18to6v3.3072x1.test2/run

**Comment by bogensch** [comment] 2022-05-31 16:14
Update: running with a different SPA remap file (map_ne30np4_to_ne256np4_highorder.20220527.nc instead of map_ne30np4_to_ne256np4_mono.20220527.nc) seems to avoid this error.  Now have OOM, so trying more procs.

**Comment by bogensch** [comment] 2022-05-31 18:08
Update: once OOM error goes away due to better PE layout, the original seg fault issue reported is back...

**Comment by bogensch** [comment] 2022-05-31 18:17
trying with fewer tasks per node in case this is still in fact an OOM

**Comment by PeterCaldwell** [comment] 2022-05-31 18:28
Also, maybe try building with the gnu rather than intel compiler.

**Comment by PeterCaldwell** [comment] 2022-05-31 21:35
@wlin7 may also have a comment about the grid coordinate mismatch.

**Comment by bartgol** [comment] 2022-05-31 21:57
Maybe we should avoid KNL for initial debugging? Maybe Chrysalis is a better choice. KNL has that limited HBM memory feature, which I don't know how default CIME launch specs are handling in a "preferred" or "exclusive" way (i.e., if alloc doesn't fit in HBM, resort to DDR4 vs crap out).

**Comment by PeterCaldwell** [comment] 2022-05-31 22:00
We also know that cori-knl wasn't BFB for SCREAMv0 runs. But I'm not sure ne256 is big enough to fit the ne256 model without pissing other users off...

**Comment by bartgol** [comment] 2022-05-31 22:07
True, but we might be able to get some time at night, and run a handful of steps. And Chrysalis nodes are much more fat than KNL ones (like 256GB/node vs 96GB+16GB/node).

**Comment by brhillman** [comment] 2022-05-31 23:08
Try an even larger tolerance?

**Comment by brhillman** [comment] 2022-05-31 23:10
Also, note that v0 needed a different value of `cubed_sphere_map` than is default for this to pass the domain check. Perhaps that's the issue here with the grid domain check?

**Comment by sarats** [comment] 2022-06-01 05:01
Just chiming in to second Luca's suggestion of trying a regular x86 machine like Chrysalis for debugging. KNL brings its own issues into the mix which are potentially unrelated to your primary problems.

**Comment by bogensch** [comment] 2022-06-01 15:52
knl update.  If i set EPS_AGRID to a very large value (in this case 1, not sure if this is doing something offensive though), we finally get through initialization to Atmosphere Step 0 where the model quickly aborts due to negative (or Nan) layer thickness.

Run directory: /global/cscratch1/sd/bogensch/e3sm_scratch/cori-knl/F2010-SCREAMv1.ne256np4_oRRS18to6v3.3072x1.test11/run

**Comment by bogensch** [comment] 2022-06-01 16:09
thanks!  on it.

**Comment by bogensch** [comment] 2022-06-01 16:54
Setting EPS_AGRID = 1e-9 and cubed_sphere_map = 2  also gets us through initialization (yay), but still negative layer thickness at Atmosphere Step = 0.  Will try again with smaller time steps.

**Comment by bogensch** [comment] 2022-06-09 16:15
Currently, SCREAMv1 master compiles the code with 72 layers by default (and this is NOT obvious to the user in the namelist and log messages regarding how many levels the model uses and needs to be addressed, but that's another issue).  So, with ne256 we were compiling with 72 layers but our intention was to run with 128 vertical levels (our initial condition file).  This confused the model leading to it to blow up, presumably because it was only reading in a subset of the data.  Compiling with 128 layers gets ne256 to run (for me it ran until debugging queue wallclock time expired) on KNL.

I made this change by manually modifying the components/scream/cime_config/config_component.xml file.  I'm sure there's someway to do this via the command line when building, but i'm too dumb to figure that out.

![Screen Shot 2022-06-09 at 9 11 27 AM](https://user-images.githubusercontent.com/25110300/172894414-b61cef40-9f98-436f-ad1a-75fb9b3d5239.png)

Finally, I feel strongly that there should be an error message given if the user is trying to compile the model with x number of levels but the initial condition file has y number of levels (like EAM does).  Having this in addition to better description in the the log/namelist files about how many levels the model thinks it is running with (again, like EAM) would have prevented us from debugging this issue for the past two weeks.

**Comment by ndkeen** [comment] 2022-06-09 16:28
Note, that while I have not been able to run this (a different error because I missed something else), I was using the following to change the levels:

```
./xmlchange SCREAM_CMAKE_OPTIONS="SCREAM_NP 4 SCREAM_NUM_VERTICAL_LEV 128 SCREAM_NUM_TRACERS 10"
```

**Comment by bartgol** [comment] 2022-06-24 22:36
The number of vertical levels is tricky when it comes to cmake. The reason why it's part of `SCREAM_CMAKE_OPTIONS` (along with the np and the number of tracers) is b/c Homme requires these three to be compile time numbers. Ideally, we should not expose nlevs and np as configurable options, and, instead, deduce them from the grid specs, and forward them to cmake at the very last moment, inside `buildlib_cmake`, by simply querying grid info. We should be able to do this mod quite easily.

The number of tracers is trickier. Homme uses it as an upper bound for allocations, but one should try to set it equal to what the model actually uses. Perhaps we could have `buildlib_cmake` deduce it from the model configuration, but that would still not be 100% safe, since between case.buiild and case.submit the user can issue some atmchange command that would change the number of tracers. I think we kind of have to leave this one in.

**Comment by brhillman** [comment] 2023-01-04 21:52
@bogensch I think we can close this issue now, as it appears it was caused by running with a different number of levels than compiled for. Please re-open if you disagree.

**Closed by brhillman** 2023-01-04 21:52 UTC
Labels: SCREAMv1
