### ISSUE TITLE
Update standalone P3 regression test to cover all lines

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#97] opened 2019-05-17 19:41 UTC
First step is to use gcov to see what is not covered. Instructions:

1. add these lines to your cmake config:
```
    -D CMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage -g -O0 -fkeep-inline-functions -fno-inline" \
    -D CMAKE_Fortran_FLAGS="-fprofile-arcs -ftest-coverage -g -O0 -fkeep-inline-functions -fno-inline" \
    -D CMAKE_EXE_LINKER_FLAGS="-lgcov" \
```

2. config and make as usual:
```
bash gcov-c-scream.sh
make -j8 p3_run_and_cmp
```

3. run the regression test:
```
ctest -R p3_regression
```

4. the gcov binary output is here:
```
./src/physics/p3/CMakeFiles/p3.dir/ascldap/users/ambradl/climate/scream/components/cam/src/physics/cam/micro_p3.F90.gcda
```
so run
```
gcov -m ./src/physics/p3/CMakeFiles/p3.dir/ascldap/users/ambradl/climate/scream/components/cam/src/physics/cam/micro_p3.F90.gcda
```
then you'll see in your current directory
```
micro_p3.F90.gcov
```
this is a text file. open it and you'll see line counts (or #### for not run)
along with code.

**Comment by ambrad** [comment] 2019-05-17 19:42
See also this page for general gcov instructions: https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/765263889/gcov+for+code+coverage

**Comment by pressel** [comment] 2019-05-23 18:21
The current regression testing does not cover homogeneous freezing of cloud liquid water ([see here](https://github.com/E3SM-Project/scream/blob/701ac104f724de8ddb4c6a63237cc5270f235cbf/components/cam/src/physics/cam/micro_p3.F90#L2212)). This lack of coverage is likely a result of the initial conditions not producing qc > qsmall when t < homogfrze. Where homogfrze = 233.16. Thus, coverage can be provided by modifying the initial condition of qc.

**Comment by ambrad** [comment] 2019-05-23 19:04
The ICs are such that T in (k,p,T), k=0 at top, reaches the critical value pretty high up:
```
   39   54266.67     231.25
   40   55655.56     233.33
```
So almost 6 km. So putting qc > 0 there might be a little unphysical. These ICs are for neither winter (lower T) nor deep Cu (qc > 0 up to the tropopause), right?

**Comment by ambrad** [comment] 2019-05-23 19:05
This might be a good reason to impl ice_case_data.py as another IC.

**Comment by ambrad** [comment] 2019-05-28 03:40
Actually, would it fix things while keeping the ICs physically meaningful to put a cirrus layer at 6 or 7 km? We'd just set qc and qr to something like 10*qsmall and perhaps 3*qsmall, respectively, for a few layers centered at ~6.5 km.

**Comment by pressel** [comment] 2019-05-28 15:35
@ambrad I think this would work, and is the sort of modification of the ICs I was thinking about in my earlier comment.  Let's chat with @PeterCaldwell about this during the microphysics telecon, he might have some alternative ideas.

**Comment by ambrad** [comment] 2019-05-29 18:12
Further analysis reveals that each of the qr and qc homogeneous freezing blocks are triggered in master's regression test, and each block affects the baseline results. So looks like we're good.

**Comment by ambrad** [comment] 2019-05-29 18:13
What about the hardcoded `log_predictSsat = .false.` line? That's making several nontrivial blocks have 0 executions.

**Comment by pressel** [comment] 2019-05-29 18:18
I think we can hold off on worrying about log_predictSsat = .false.  for now. There is a PR coming very soon that introduces a lot of nontrivial changes to how P3 deals with supersaturation so we should probably worry about coverage at that point. @AaronDonahue may have another opinion though as he actively doing that development.

**Comment by AaronDonahue** [comment] 2019-05-29 19:10
PR #103 will probably remove all references to log_predictSsat entirely so it shouldn't be a problem.

**Comment by bartgol** [comment] 2020-09-04 04:52
@AaronDonahue @pressel @ambrad Is this issue still relevant?

**Comment by bartgol** [comment] 2021-06-30 21:29
@jgfouca , given the struggle you're going through to fix all the fpes that went under the radar, should we consider tackling this issue sooner than later? We can easily set up a gcov build on jenkins, maybe run it only with the nightlies (rather than with every PR), and take it from there... Might save us debug time later, if there's a code path that is currently never tested but ends up getting hit in the future...

**Comment by jgfouca** [comment] 2021-06-30 21:53
@bartgol , it looks like Cdash supports the uploading of coverage data, so that could provide a nice way of displaying this data to the team, which would increase its value. It seems like @PeterCaldwell wants this since he labelled it as high priority. I will assign this to myself since it involves cdash and test infrastructure.

**Comment by PeterCaldwell** [comment] 2021-06-30 22:00
I assigned it high priority ages ago and had forgotten. I agree with Luca that testing code coverage would help us avoid bugs and should therefore get done. I see finishing all the pieces needed for v1 to be slightly higher priority though... So don't drop the interpolation task in favor of this one on my account (though I don't mind if you tackle both at the same time)

**Closed** 2021-07-21 18:40 UTC
Labels: priority:high, testing
