### ISSUE TITLE
KERNEL CHECK Problems with T values on pm-gpu (using scream-small_kernels testmod)

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1992] opened 2022-10-14 20:37 UTC
With master of oct14th that includes upstream merge, I see fails with

`SMS.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-gpu_gnugpu.scream-small_kernels`

```
1: :0: : block: [1646,0,0], thread: [0,65,0] Assertion `` failed.
1: :0: : block: [1646,0,0], thread: [0,66,0] Assertion `` failed.
1: :0: : block: [1646,0,0], thread: [0,67,0] Assertion `` failed.
1: :0: : block: [1645,0,0], thread: [0,65,0] Assertion `` failed.
1: :0: : block: [1645,0,0], thread: [0,66,0] Assertion `` failed.
1: :0: : block: [1645,0,0], thread: [0,67,0] Assertion `` failed.
1: KERNEL CHECK FAILED:
1:    !(is_neg_Tl1_1.any())
1:    Error! Tl1_1 has <= 0 values.
```

in DEBUG, I see:

```
1: KERNEL CHECK FAILED:
1:    !(is_nan_t_atm.any())
1:    Error! Temperature has NaN values.
...

1: :0: : block: [1615,0,0], thread: [0,63,0] Assertion `` failed.
1: terminate called after throwing an instance of 'std::runtime_error'
1:   what():  cudaStreamSynchronize(stream) error( cudaErrorAssert): device-side assert triggered /global/cfs/cdirs/e3sm/ndk/se37-oct14/externals/ekat/extern/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:162
1: 

```

Cases without small_kernel mod work:
```
SMS.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-gpu_gnugpu
SMS_D.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-gpu_gnugpu
```

**Comment by ndkeen** [comment] 2022-10-21 21:01
Hmm, OK, so with Oct 21 scream master, I tried these again. The default number of nodes for ne30 on pm-gpu is 2 and those still fail in the same way as above.  But with 4 nodes, it completes.

```
SMS_D_P16.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-gpu_gnugpu.scream-small_kernels
```

**Comment by bartgol** [comment] 2022-10-24 16:48
The small-kernels version of shoc does have a few persistent views that the monolithic one doesn't. I think they use the atm buffer though, so I don't know exactly how much _more_ memory they require. The AD should, however, print a memory usage (in terms of resolution-dependent host/device views). Perhaps comparing the output you get now, from a version of master before the small kernels PR might show the diff.

Also, pinging @jgfouca since he might know more.

**Comment by jgfouca** [comment] 2022-10-24 17:14
I've been looking at this for a few days now since this is showing up on our dashboard as a failure. I'm seeing the exact same failure and saw that `ne4_ne4` worked fine, it was `ne30pg2_ne30pg2` where I see the problem. I'm trying to figure out where to go from here.

**Comment by jgfouca** [comment] 2022-10-27 19:25
@ambrad , I haven't looked at this in a couple day. I need to find where/why that NaN is getting introduced. Does FPE=On work on GPU?

**Comment by ambrad** [comment] 2022-10-27 20:09
No: https://docs.nvidia.com/cuda/floating-point/index.html#differences-from-x86. But PEM_Ld100.ne4pg2 is a good place to start to first confirm or rule out nondeterminism and PE-layout variance. After that, we may have to do an output comparison between monolithic and small kernels, at which point I would suggest involving me, as I have tools to do those types of comparisons.

**Comment by ndkeen** [comment] 2022-10-27 22:46
fwiw, I tried 3 different PE layouts (8,16,32 nodes) of the SMS test on cori-knl and all were identical (looking at cprnc of scream.hi file)

**Comment by ambrad** [comment] 2022-10-27 23:11
The next thing to look at is comparing the output of two ne30pg2 runs of length 90 days with monolithic and small kernels. It's not clear to me whether to expect optimization-based diffs. Comparing two _D runs first might be fruitful.

**Comment by jgfouca** [comment] 2022-10-28 16:52
@ambrad , @ndkeen : 

```
Waiting for tests to finish
PASS PEM_D_Ld100.ne4pg2_ne4pg2.F2010-SCREAMv1.pm-gpu_gnugpu.scream-small_kernels RUN
    Case dir: /pscratch/sd/a/acmetest/e3sm_scratch/pm-gpu/PEM_D_Ld100.ne4pg2_ne4pg2.F2010-SCREAMv1.pm-gpu_gnugpu.scream-small_kernels.20221027_131929_xn9ahk
test-scheduler took 25258.484911441803 seconds
```

I will try a 90-day comparison run SK vs. MK.

**Comment by ndkeen** [comment] 2022-10-28 22:59
Trying to run longer, these fail with the same kernel check failure:

```
PEM_P16_Ld20.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-gpu_gnugpu.scream-small_kernels
PEM_D_P16_Ld20.ne30pg2_ne30pg2.F2010-SCREAMv1.pm-gpu_gnugpu.scream-small_kernels
```

above, I noted that the 5 day tests passed.

**Comment by ambrad** [comment] 2022-10-31 18:25
I'm going to take this task to free up Jim for other things.

**Comment by ambrad** [comment] 2022-11-02 22:44
On Ascent, I find that F2010-SCREAMv1-noAero.ne30pg2_ne30pg2 is identical to 5 days if I add `--fmad=false` to nvcc_wrapper:
```
base) [ambradl@login1.ascent kokkos]$ pwd
/ccsopen/home/ambradl/repo/SCREAMref/externals/ekat/extern/kokkos
(base) [ambradl@login1.ascent kokkos]$ git diff
diff --git a/bin/nvcc_wrapper b/bin/nvcc_wrapper
index e1a208813..33fb2da5c 100755
--- a/bin/nvcc_wrapper
+++ b/bin/nvcc_wrapper
@@ -41,7 +41,7 @@ cpp_files=""
 xcompiler_args=""

 # Cuda (NVCC) only arguments
-cuda_args=""
+cuda_args="--fmad=false"

 # Arguments for both NVCC and Host compiler
 shared_args=""
@@ -607,6 +607,7 @@ else
 fi

 nvcc_command="$nvcc_command $compile_arg $output_arg"
+echo $nvcc_command

 #Print command for dryrun
 if [ $dry_run -eq 1 ]; then
```
Next, I'll switch to PM and see if this result holds there, too.

**Comment by ambrad** [comment] 2022-11-03 00:41
On PM GPU, `--fmad=false` has the same effect: the small-kernel and monolithic-kernel runs switch from diff'ing to being BFB. This is for 5 days with the following compset and PE layout:
```
    compset=F2010-SCREAMv1
    res=ne30pg2_ne30pg2

    ./xmlchange NTASKS=16
    ./xmlchange MAX_TASKS_PER_NODE=4
    ./xmlchange MAX_MPITASKS_PER_NODE=4
    ./xmlchange NTHRDS=1
```
The next thing to do is to look at the case of the PE layout used in the test. It appears to use 2 nodes, 8 GPUs, 16 threads/rank.

**Comment by ambrad** [comment] 2022-11-03 01:05
I reproduce the issue with 2x4x16 and 2x4x1 (nnode x ngpu x n(host)threads). Next, I'll use the BFBness I can get with `--fmad=false` to figure out what the issue is when the number of GPUs is small, which I think must be the issue given the evidence available at this point.

**Comment by ambrad** [comment] 2022-11-03 19:13
I'm switching back to Ascent because I can reproduce the issue there with 1x6: in summary, `--fmad=false` gives BFB results between SK and MK until the GPU count gets too small, at which point SK fails.

**Comment by ambrad** [comment] 2022-11-08 23:34
Update. I've found three bugs and am now working on checking whether the fixes are enough:

1. kbfs; fixed in https://github.com/E3SM-Project/scream/pull/2017
2. pblh treatment in shoc_pblintd_disp/impl
3. in EKAT `TeamUtils` for GPU, need `Kokkos::memory_fence()` in `get/release_workspace_idx`.

**Closed** 2022-11-12 17:31 UTC
Labels: pm-gpu
