### ISSUE TITLE
Incorrect restart writing behavior

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#2110] opened 2022-12-28 21:00 UTC
I'm not sure if this an issue or not, but wanted to document to remind myself of details.

I launched a case to run for 1 month, with a restart at the end. I then continued it for another month. All fine.
Then I wanted to continue for 10 more days with a restart every 5th day. Not that it matters, but the reason
for this was to get a restart closer to a crash. 
```
Results in group run_begin_stop_restart
        STOP_N: 10
        STOP_OPTION: ndays
        REST_N: 5
        REST_OPTION: ndays
        CONTINUE_RUN: TRUE
```
The run completed, but I don't see the `scream.r` restarts being written. Normally, I would see a restart file written for elm,cice,scream,cpl, which is true for the 2 jobs that run for a month. But for the job running for 10 days, with 5-day restarts, I don't see any new scream.r files ?

```
login17% lr run/*.r.*
  402200488 Dec 28 11:17 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.elm.r.0001-02-01-00000.nc
    6060120 Dec 28 11:17 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.cice.r.0001-02-01-00000.nc
 1072756880 Dec 28 11:17 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.scream.r.0001-02-01-00000.nc
   41796488 Dec 28 11:17 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.cpl.r.0001-02-01-00000.nc
    6060120 Dec 28 11:58 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.cice.r.0001-03-01-00000.nc
  402200488 Dec 28 11:58 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.elm.r.0001-03-01-00000.nc
 1072756880 Dec 28 11:58 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.scream.r.0001-03-01-00000.nc
   41796488 Dec 28 11:58 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.cpl.r.0001-03-01-00000.nc
    6060120 Dec 28 12:03 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.cice.r.0001-03-06-00000.nc
  402200488 Dec 28 12:03 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.elm.r.0001-03-06-00000.nc
   41796488 Dec 28 12:03 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.cpl.r.0001-03-06-00000.nc
    6060120 Dec 28 12:04 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.cice.r.0001-03-11-00000.nc
  402200488 Dec 28 12:04 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.elm.r.0001-03-11-00000.nc
   41796488 Dec 28 12:04 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.cpl.r.0001-03-11-00000.nc

/pscratch/sd/n/ndk/e3sm_scratch/pm-gpu/se48-dec26/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2
```

And, looking at rpointer files, I see:
```
atmdate=0001-03-01-00000
drvdate=0001-03-11-00000
lnddate=0001-03-11-00000
icedate=0001-03-11-00000
ocndate=0001-03-11-00000
```
ie, the date in rpointer.atm appears to be the wrong date? (and, of course, there are no restart files for ATM)

**Comment by bartgol** [comment] 2023-01-09 19:27
Just reading this after returning from vacation. 

> ```
> Results in group run_begin_stop_restart
>         STOP_N: 10
>         STOP_OPTION: ndays
>         REST_N: 5
>         REST_OPTION: ndays
>         CONTINUE_RUN: TRUE
> ```
For the 5-days restart job, can you check what was the content of this sublist in the `scream_input.yaml` file in `run/data`? It should contain
```
Scorpio:
  model_restart:
    Casename: <your_case_name>
    output_control:
      Frequency:       5
      frequency_units: nsteps
```
but maybe something is amiss in our restart logic. If that's indeed the yaml file content, then we need to check what else could prevent the writing of the restart file.

**Comment by ambrad** [comment] 2023-01-09 20:38
@bartgol are you going to take this issue? If so, assign yourself and remove the "help wanted" tag. I'm pushing us to try to keep the "help wanted" issues a tidy list of immediately actionable dev items up for grabs so devs always have something to do when they have free cycles.

**Comment by ndkeen** [comment] 2023-01-09 20:43
Luca: indeed it looks like `run/data/scream)input.yaml` not updating the frequency units?

```
login20% head -16 run/data/scream_input.yaml
################################################################
# Do NOT modify this file. It is generated by scream/buildnml using
# the data from $case/namelist_scream.xml. If you want to make some
# local changes, you can edit this XML file or use atmchange.
################################################################
Scorpio:
  model_restart:
    Casename: ./f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.scream
    output_control:
      Frequency: 1
      avg_type_in_filename: false
      frequency_in_filename: false
      frequency_units: nmonths
  output_yaml_files:
  - /pscratch/sd/n/ndk/e3sm_scratch/pm-gpu/se48-dec26/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2/run/data/spiffy.yaml
atmosphere_processes:
```

**Comment by ambrad** [comment] 2023-01-09 20:51
Noel, I'm pretty sure you just need to run something like
```
./atmchange Scorpio::model_restart::Frequency = 5
./atmchange Scorpio::model_restart::frequency_units = ndays
```

**Comment by ndkeen** [comment] 2023-01-09 20:53
Sure, if this is not an issue, can close and next time I need this I can try to remember to do the atmchanges. Just thought it might not be expected behavior.

**Comment by bartgol** [comment] 2023-01-09 21:38
I think that might be right. I was talking to @jgfouca  a while ago, to see if we can inject some atm script every time that xmlchange runs. Namely, I want the atm buildnml to re-parse case related vars to see if we need to update some entries. I suspect that's not possible (at least not easily), and I have a backup solution in mind, which I need to discuss with Jim. Ultimately, we want to atm input to be fine in your use case (the user should not have to run those atmchange if the changes are the same as the XML ones).

Alas, for now I think Andrew's suggestion is your best/quickest solution.

**Comment by jgfouca** [comment] 2023-01-17 17:44
Assigning to myself and changing to enhancement. The integration between xmlchange and atmchange needs to be a bit smarter to catch cases like this.

**Comment by ambrad** [comment] 2023-01-20 20:48
@PeterCaldwell I noticed you put "help wanted" back on this after Jim assigned himself. Are you looking for a label that helps you find what is actively being addressed? We can add something like "in progress" so that we go from "help wanted" to (assignee, "in progress").

**Comment by PeterCaldwell** [comment] 2023-01-20 20:55
Oh sorry. I hadn't appreciated that we were removing "help wanted" once help was found. In retrospect that's the obvious thing to do. I agree that label should be removed and no need to add an "in progress" flag.

**Comment by jgfouca** [comment] 2023-03-06 16:37
@ndkeen , I almost have a fix ready.

**Comment by ndkeen** [comment] 2023-03-07 17:28
I was trying out the branch in PR #2214 and perhaps it will address some of the issues documented here, but I do still see at least one of the odd behaviors.

In this case:
/pscratch/sd/n/ndk/e3sm_scratch/pm-gpu/jfbuild/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.jfbuild.gnugpu.L128.1m.n004a4xX14444.rtest

I'm still trying to work out exactly what needs to happen to reproduce these issues (was assuming it was a single bug somewhere, but perhaps not). What I've been doing is create a new case, then restart at least twice, changing the STOP_N/REST_N each time. I first created with STOP_N=6, REST_N=3.
Then I set CONTINUE_RUN=TRUE.
The first restart was with STOP_N=2, REST_N=1, ./atmchange Scorpio::model_restart::output_control::Frequency=1
Which seems OK. But then changing back to: STOP_N=6, REST_N=3, ./atmchange Scorpio::model_restart::output_control::Frequency=3 is where I see a problem.
The scream.r files are "out-of-sync".

**Comment by bartgol** [comment] 2023-03-07 17:53
So, to recap

- 1st run, initial run, REST_N=3, STOP_N=6: should generate rest files with 0001-04-01 and 0001-07-01 stamps. Works.
- 2nd run, restarted run (from 07-01), REST_N=1,STOP_N=2, should generate rest files with 0001-08-01 and 0001-09-01 stamps. Works.
- 3rd run, restarted run (from 09-01), REST_N=3,STOP_N=6, should generate rest files with 0001-12-01 and 0002-03-01 stamps. Fails for scream, which seems to use REST_N=1 for first file and REST_N=3 for second.
- In all of the above runs, STOP_OPT=REST_OPT=nmonths.

Is that correct ?

The most puzzling thing is, in the 3rd run, why scream seems to use REST_N=1 for first restart and then back to the correct REST_N=3 for the second. It would be nice to know for sure if the restart is written at the correct time (but happens to have the wrong timestamp). Do you know what the value of `time` is in the two "wrong" restarts? I wonder if it is correct (so scream does generate the correct restart data), but we mess up the timestamp in the filename, or if scream indeed tries to write a restart at the wrong time. I'm guessing it is the latter, and it is likely all due to timestamp book keeping in the IO classes.

**Comment by ndkeen** [comment] 2023-03-07 17:59
Using nmonths for each -- we already know there may also be challenges with mixing up units.

Currently in the case:
```
./xmlquery STOP_N,STOP_OPTION,REST_N,REST_OPTION,CONTINUE_RUN

Results in group run_begin_stop_restart
        STOP_N: 6
        STOP_OPTION: nmonths
        REST_N: 3
        REST_OPTION: nmonths
        CONTINUE_RUN: TRUE

./atmquery Scorpio::model_restart::output_control::Frequency,Scorpio::model_restart::output_control::frequency_units

    output_control::Frequency: 3
    output_control::frequency_units: nmonths
```

Regarding `ncdump -h` on the restart files, for `time` I only see `time = UNLIMITED ; // (1 currently)`

**Comment by jgfouca** [comment] 2023-03-07 18:02
Is there any way to write a test for this?

**Comment by bartgol** [comment] 2023-03-07 22:32
> Regarding `ncdump -h` on the restart files, for `time` I only see `time = UNLIMITED ; // (1 currently)`

What about `ncdump -v time`?

**Comment by ndkeen** [comment] 2023-03-08 21:39
Let's leave this open until all of the issues are addressed

**Comment by ndkeen** [comment] 2023-03-09 20:59
Answering Luca question about `ncdump -v time`:
```
(e3sm_unified_1.8.1_nompi) login27% ncdump -v time run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.jfbuild.gnugpu.L128.1m.n004a4xX14444.rtest.scream.r.0002-01-01-00000.nc > & lo
(e3sm_unified_1.8.1_nompi) login27% ncdump -h run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.jfbuild.gnugpu.L128.1m.n004a4xX14444.rtest.scream.r.0002-01-01-00000.nc > & loh
(e3sm_unified_1.8.1_nompi) login27% diff lo loh
106,108d105
< data:
< 
<  time = 365 ;
```

**Comment by bartgol** [comment] 2023-03-09 22:47
So scream _is_ indeed lagging behind with its timestamp, it's not just a matter of the string in the file...

**Comment by ndkeen** [comment] 2023-03-10 22:35
I can reproduce with ne4 on pm-cpu.  First run 1 month with a restart.  Then another month with restart. All fine. Then run 6 more months, with a restart every 3rd month. Finally, run another month.  It looks like the run for 6 months is leaving the rpointer pointing to what looks like the wrong date for scream.r, but the simulation continues as normal.

```
login23% zgrep "Reading restart" run/*log*
run/cpl.log.6004187.230310-115222.gz:(seq_mct_drv) Reading restart file f4cpu.F2010-SCREAMv1.ne4pg2_ne4pg2.se58-mar9.gnu.n001a96x1c8.cpl.r.0001-02-01-00000.nc
run/cpl.log.6004202.230310-115555.gz:(seq_mct_drv) Reading restart file f4cpu.F2010-SCREAMv1.ne4pg2_ne4pg2.se58-mar9.gnu.n001a96x1c8.cpl.r.0001-03-01-00000.nc
run/cpl.log.6006267.230310-142143.gz:(seq_mct_drv) Reading restart file f4cpu.F2010-SCREAMv1.ne4pg2_ne4pg2.se58-mar9.gnu.n001a96x1c8.cpl.r.0001-09-01-00000.nc
Binary file run/lnd.log.6004187.230310-115222.gz matches
Binary file run/lnd.log.6004202.230310-115555.gz matches
Binary file run/lnd.log.6006267.230310-142143.gz matches
login23% zgrep "Reading restart" run/cpl.log.600*
run/cpl.log.6004187.230310-115222.gz:(seq_mct_drv) Reading restart file f4cpu.F2010-SCREAMv1.ne4pg2_ne4pg2.se58-mar9.gnu.n001a96x1c8.cpl.r.0001-02-01-00000.nc
run/cpl.log.6004202.230310-115555.gz:(seq_mct_drv) Reading restart file f4cpu.F2010-SCREAMv1.ne4pg2_ne4pg2.se58-mar9.gnu.n001a96x1c8.cpl.r.0001-03-01-00000.nc
run/cpl.log.6006267.230310-142143.gz:(seq_mct_drv) Reading restart file f4cpu.F2010-SCREAMv1.ne4pg2_ne4pg2.se58-mar9.gnu.n001a96x1c8.cpl.r.0001-09-01-00000.nc
login23% zgrep filename run/atm.l*
run/atm.log.6004084.230310-114135.gz:        filename: /global/cfs/cdirs/e3sm/inputdata/atm/scream/init/screami_ne4np4L72_20220823.nc
run/atm.log.6004084.230310-114135.gz:        filename: /global/cfs/cdirs/e3sm/inputdata/atm/cam/topo/USGS-gtopo30_ne4np4pg2_16x_converted.c20200527.nc
run/atm.log.6004187.230310-115222:        filename: ./f4cpu.F2010-SCREAMv1.ne4pg2_ne4pg2.se58-mar9.gnu.n001a96x1c8.scream.r.0001-02-01-00000.nc
run/atm.log.6004187.230310-115222:        filename: ./f4cpu.F2010-SCREAMv1.ne4pg2_ne4pg2.se58-mar9.gnu.n001a96x1c8.scream.r.0001-02-01-00000.nc
run/atm.log.6004187.230310-115222.gz:        filename: ./f4cpu.F2010-SCREAMv1.ne4pg2_ne4pg2.se58-mar9.gnu.n001a96x1c8.scream.r.0001-02-01-00000.nc
run/atm.log.6004187.230310-115222.gz:        filename: ./f4cpu.F2010-SCREAMv1.ne4pg2_ne4pg2.se58-mar9.gnu.n001a96x1c8.scream.r.0001-02-01-00000.nc
run/atm.log.6004202.230310-115555.gz:        filename: ./f4cpu.F2010-SCREAMv1.ne4pg2_ne4pg2.se58-mar9.gnu.n001a96x1c8.scream.r.0001-03-01-00000.nc
run/atm.log.6004202.230310-115555.gz:        filename: ./f4cpu.F2010-SCREAMv1.ne4pg2_ne4pg2.se58-mar9.gnu.n001a96x1c8.scream.r.0001-03-01-00000.nc
run/atm.log.6006267.230310-142143.gz:        filename: ./f4cpu.F2010-SCREAMv1.ne4pg2_ne4pg2.se58-mar9.gnu.n001a96x1c8.scream.r.0001-07-01-00000.nc
run/atm.log.6006267.230310-142143.gz:        filename: ./f4cpu.F2010-SCREAMv1.ne4pg2_ne4pg2.se58-mar9.gnu.n001a96x1c8.scream.r.0001-07-01-00000.nc
login23% zgrep "Using restart dump" run/ice.log.600*
run/ice.log.6004187.230310-115222.gz: Using restart dump=f4cpu.F2010-SCREAMv1.ne4pg2_ne4pg2.se58-mar9.gnu.n001a96x1c8.cice.r.0001-02-01-00000.nc
run/ice.log.6004202.230310-115555.gz: Using restart dump=f4cpu.F2010-SCREAMv1.ne4pg2_ne4pg2.se58-mar9.gnu.n001a96x1c8.cice.r.0001-03-01-00000.nc
run/ice.log.6006267.230310-142143.gz: Using restart dump=f4cpu.F2010-SCREAMv1.ne4pg2_ne4pg2.se58-mar9.gnu.n001a96x1c8.cice.r.0001-09-01-00000.nc
login23% .
/pscratch/sd/n/ndk/e3sm_scratch/pm-cpu/se58-mar9/f4cpu.F2010-SCREAMv1.ne4pg2_ne4pg2.se58-mar9.gnu.n001a96x1c8
```

**Comment by ndkeen** [comment] 2023-03-15 21:12
For another longer running case, I ran 3 years, and then just now asked to run 2 more jobs for 1 month each (with restart).  The first job was OK, but after the second, the dates of restart files are out of sync -- with scream restart being behind 1 month.  If I were to restart, I assume it would use that file which seems like would be incorrect.

`/pscratch/sd/n/ndk/e3sm_scratch/pm-gpu/se55-feb24/t.se55-feb24.F2010-SCREAMv1.ne120pg2_ne120pg2.pm-gpu.n085t4xX.L128.vth200`

**Comment by AaronDonahue** [comment] 2023-03-17 20:52
I've recreated the problem using just 1 step rather than 1 month.  So thats a much faster recreator.  I also ran a few other simulations to compare as baselines:
All runs take 8 steps
Baseline: no restart, output every step, restart written every step.
Freq_1:  restart every step, restart written every step
Freq_2: restart every two steps, restart written every two steps
Mixed: Noels case - run 1 step, write restart - run 6 more steps writing restarts every 3 steps - run 1 more step.Using cprnc I confirmed that Baseline = Freq_1 = Freq_2 for all scream files.  But there was 1 DIFF when comparing Baseline w/ Mixed for the final output file.

**Comment by AaronDonahue** [comment] 2023-03-17 20:54
Freq_1 Case:
```
>> zgrep filename run/atm.l*
run/atm.log.13604146.230317-113948.gz:    [EAMxx] IC filename: /usr/gdata/climdat/ccsm3data/inputdata/atm/scream/init/screami_ne4np4L72_20220823.nc
run/atm.log.13604146.230317-113948.gz:        filename: /usr/gdata/climdat/ccsm3data/inputdata/atm/cam/topo/USGS-gtopo30_ne4np4pg2_16x_converted.c20200527.nc
run/atm.log.13604151.230317-114041.gz:    [EAMxx] Restart filename: ./SMS_Ln8_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.restart_test_freq_1.scream.r.0001-01-01-03600.nc
run/atm.log.13604152.230317-114140.gz:    [EAMxx] Restart filename: ./SMS_Ln8_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.restart_test_freq_1.scream.r.0001-01-01-07200.nc
run/atm.log.13604156.230317-114240.gz:    [EAMxx] Restart filename: ./SMS_Ln8_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.restart_test_freq_1.scream.r.0001-01-01-10800.nc
run/atm.log.13604157.230317-114340.gz:    [EAMxx] Restart filename: ./SMS_Ln8_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.restart_test_freq_1.scream.r.0001-01-01-14400.nc
run/atm.log.13604163.230317-114440.gz:    [EAMxx] Restart filename: ./SMS_Ln8_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.restart_test_freq_1.scream.r.0001-01-01-18000.nc
run/atm.log.13604164.230317-114540.gz:    [EAMxx] Restart filename: ./SMS_Ln8_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.restart_test_freq_1.scream.r.0001-01-01-21600.nc
run/atm.log.13604167.230317-114640.gz:    [EAMxx] Restart filename: ./SMS_Ln8_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.restart_test_freq_1.scream.r.0001-01-01-25200.nc
```

**Comment by AaronDonahue** [comment] 2023-03-17 20:56
Results of my quick cprnc checker:
```
(e3smplot) [donahue5@quartz2300:run]$ python check_case.py 
baseline.scream.hi.0001-01-01-07200.nc are IDENTICAL
baseline.scream.r.0001-01-01-03600.nc are IDENTICAL
baseline.scream.hi.0001-01-01-00000.nc are IDENTICAL
baseline.scream.r.0001-01-01-21600.nc are IDENTICAL
baseline.scream.r.0001-01-01-10800.nc are IDENTICAL
baseline.scream.hi.0001-01-01-18000.nc are IDENTICAL
baseline.scream.hi.0001-01-01-25200.nc are IDENTICAL
baseline.scream.hi.0001-01-01-14400.nc are IDENTICAL
baseline.scream.hi.0001-01-01-03600.nc are IDENTICAL
baseline.scream.hi.0001-01-01-28800.nc are DIFFERENT
baseline.scream.hi.0001-01-01-10800.nc are IDENTICAL
baseline.scream.hi.0001-01-01-21600.nc are IDENTICAL
```
Note, to keep things readable I cut the long string of the file names and I'm comparing the file from baseline against the mixed file in this case.

**Comment by AaronDonahue** [comment] 2023-03-17 21:12
Yes, that's my interpretation.  And note that a comparison of the restart files themselves shows they match.

**Comment by AaronDonahue** [comment] 2023-03-17 21:13
I should also note, I am running master at this location:
```
commit e48271df9996e6d0bf81a6d4c3c7ae1dfbbb0298 (HEAD)
Merge: f1943cd8e0 037aedda61
Author: Autotester for E3SM related projects <56648600+E3SM-Autotester@users.noreply.github.com>
Date:   Wed Mar 15 14:53:31 2023 -0600

    Merge Pull Request #2245 from E3SM-Project/scream/bartgol/revert-cxx-17
    
    Automatically Merged using E3SM Pull Request AutoTester
    PR Title: Revert upgrade to CXX17
    PR Author: bartgol
```

**Comment by AaronDonahue** [comment] 2023-03-17 21:30
@bartgol , perhaps serendipity, the rpointer keeps a running log of the restart files.  If we look at the mixed case we would expect the timestamp on the entries to follow the pattern of dt, 4*dt, 7*dt right?  Because we run one step and restart at dt, then we restart w/ a freq of 3dt, so the next one will be dt+3dt, then dt+3dt+3dt.  That is not what we get:
```
./SMS_Ln8_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.restart_test_mix_freq.scream.r.0001-01-01-03600.nc
./SMS_Ln8_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.restart_test_mix_freq.scream.r.0001-01-01-10800.nc
./SMS_Ln8_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.restart_test_mix_freq.scream.r.0001-01-01-21600.nc
```
Instead the pattern is dt, dt+2dt, dt+2dt+3dt.

So maybe that second entry is actually because it thinks it needs to restart w/ a frequency of 3 and has already started at 1

**Comment by AaronDonahue** [comment] 2023-03-17 21:32
If my theory is correct then changing to REST_N=5 and running for a few more steps should produce the next restart at 10dt instead of 11dt which would be what is expected.

**Comment by AaronDonahue** [comment] 2023-03-17 21:41
okay, so I ran two more experiments:
Changed REST_N=5, STOP_N=15 - so ran for 15 more steps from the above state which should used `./SMS_Ln8_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.restart_test_mix_freq.scream.r.0001-01-01-21600.nc` as the restart.
This created the restart files:
```
./SMS_Ln8_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.restart_test_mix_freq.scream.r.0001-01-01-39600.nc
./SMS_Ln8_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.restart_test_mix_freq.scream.r.0001-01-01-57600.nc
./SMS_Ln8_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.restart_test_mix_freq.scream.r.0001-01-01-75600.nc
```

Then I changed REST_N=25 - so ran another 15 steps now w/ restart every 25 steps. which used `./SMS_Ln8_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.restart_test_mix_freq.scream.r.0001-01-01-75600.nc` to restart.  This produced the restart file
```
./SMS_Ln8_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.restart_test_mix_freq.scream.r.0001-01-02-10800.nc
```

**Comment by AaronDonahue** [comment] 2023-03-17 21:43
that last restart is clearly wrong.  if only 15 steps and a REST_N=25 steps no restart should have written.  What's more, `02-10800` is the 27th hour (dt=3600).

**Comment by AaronDonahue** [comment] 2023-03-17 21:52
tunneling in on the possible issue:
```
[EAMxx] initialize_atm_procs ... done!
[EAMxx::init] resolution-dependent device memory footprint: 1.260328MB
Atmosphere step = 20
  model time = 0001-01-01 22:00:00
```

From the last run.  Up until now the hour was 1+"Atmosphere Step" and the hour = restart_timestamp/3600.  Here there is a 1 hour descrepency.

**Comment by bartgol** [comment] 2023-03-17 21:57
So the REST_N=25 should have produced a restart at the Start_t+REST_N=21h+25h=46h, so 02-79200, right? Are you sure the REST_N=25 run used the t=21h as restart file? And does that file seem to store the correct case start date/time?

**Comment by AaronDonahue** [comment] 2023-03-17 23:12
```
atm.log.13604743.230317-143548.gz:    [EAMxx] Restart filename: ./SMS_Ln8_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.quartz_intel.restart_test_mix_freq.scream.r.0001-01-01-75600.nc
```
did you the 21 hour restart file, see above.  It shouldn't have produced a restart write at all, it only ran 15 steps.

**Comment by AaronDonahue** [comment] 2023-03-20 18:34
Alright, I think I have tracked this issue down.  It is due to how we set SCREAM to interpret restart frequency vs. how all other model components do.  Noel hinted at the problem in his assessment that SCREAM seemed to be missing a restart write.

In SCREAM, the restart frequency (lets call it REST_N) is compared against the timestamp and if `mod(nsteps,REST_N*REST_OPTION/dt)==0` then a restart is written.  No matter what.  So w/ @ndkeen 's example above, you scream would write a restart at N=1, 3, and 6.  1 - because REST_N=1, then restart the run with REST_N=3 so then write at 3 and 6, both multiples of 3.

For the rest of E3SM the restart frequency is based on the number of local steps taken.  So the same scenario should have a restart written at 1, 4 and 7.  

So the restarts are off by 1.  Now each component owns what goes in the `rpointer` file and all E3SM does is mine that for info.  So no error gets thrown when the rpointer files all point to files w/ different timestamps.  Those files exist and are loaded.  no problem.

**Comment by AaronDonahue** [comment] 2023-03-20 18:37
The solution will be

a) To make scream match the behavior of the other components.

b) We should have some kind of check that makes sure that this inconsistency doesn't happen again.  Either the simulation was out-of-sync w/ the atmosphere - or with the other components.  I don't know off-hand who dictates the starting timestamp for a restart run, I suspect CIME passes that the coupler.  So SCREAM should be using that timestamp and checking the rpointer  timestamp and at least throw a WARNING that there i something not matching.

**Comment by AaronDonahue** [comment] 2023-03-20 18:40
I'll start work on (a).

Note to others.  If this is in fact the only issue then it says we can trust our restarts provided we haven't changed REST_N midstream.  It points to a bookkeeping problem, not an inherent problem in how we write/read restarts.

**Closed** 2023-03-24 01:07 UTC
Labels: enhancement, Atmosphere Driver, priority:medium
