### ISSUE TITLE
Albedo out of bounds due to remapping from surface components

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#1597] opened 2022-05-02 23:24 UTC
We're struggling with model fails due to albedo>1. Sometimes they are roundoff level, but they've been as big as 1.2. If errors were at roundoff level, we could just correct the problem... but that would hide the fact that sometimes something more evil seems to be happening.

Wuyin says albedo was well behaved in a run with ocean and atm on ne4 grid but out of bounds when atm=ne4 and ocn=oqu240. It seems unlikely that the physical calculation of albedo wouldn't be clipped at 1, so we suspect the problem is with regridding. Have we ever seen these albedo-out-of-bounds errors in a case where ocean was on the same grid as atm? I think we're mainly seeing them in ne120 runs, where we are using a different ocean grid because we don't have the right inputdata...

Open questions:
1. do we have any examples where this is happening where atm2ocn is the identity grid? Or anything other than ne120?
2. what map are we using in these cases that fail? for ne120, it looks like we're using map_ne120np4_to_oRRS18to6v3_aave.170111.nc or map_ne120np4_to_oRRS18to6v3_conserve.170111.nc
3. Do we expect these maps to be conservative? I don't know their details...

**Comment by wlin7** [comment] 2022-05-03 17:25
The aave maps are conservative. 
Just did a mappping test of the map files used in the ne120 run (grid ne120_r0125_oRRS18to6v3).

With unity values everywhere on oRRS18to6v3, the remapped values on ne120 grids using map_oRRS18to6v3_to_ne120np4_aave.170111.nc never exceed 1.0.

Similarly with unity values on r0125 land grids, using map file map_r0125_to_ne120np4_mono.200508.nc, the remapped data on ne120 grids has a max of 1.000000238. 

The large albedo values as large as 1.2+ do not appear to be due to map files.

**Comment by PeterCaldwell** [comment] 2022-05-03 17:31
So you're saying that mono maps *do* create spurious maxima though? Was the 1.000000238 generated by remapping a file that was one everywhere on the r0125 grid? I would have thought that you'd need gradients in the source grid to have overshoots on the destination grid.

**Comment by wlin7** [comment] 2022-05-03 17:51
Yeah, the source data is 1.0 everywhere on r0125 grid. Don't have an explanation why overshoot happens. This is from finer to coarser grid remapping.  A remapping from ne120 to r0125, using the corresponding map file map_ne120np4_to_r0125_mono.20200508.nc, no overshooting occurs.

**Comment by PeterCaldwell** [comment] 2022-05-03 18:22
Comment from Luke: "If this is over the open ocean (not near the sea ice) I think the calculation of albedo is just a function of latitude and day of year and that calculation is in the coupler.  MPAS-Ocean has no internal albedo calculation.  If you are near the sea ice margin the albedo calculation in MPAS-SI/CICE may be the issue. I asked jon to take a quick look at the coupler to see if there is some way albedo could exceed 1, I’ll let you know if I hear anything.  But do let me know if these bad albedos are near the sea ice and we can look there too."

**Comment by PeterCaldwell** [comment] 2022-05-03 18:54
@wlin7 - could you retry the r0125->ne120 mono map with some entries set to zero instead of 1? My suspicion is that this will make the overshoots worse. 

Also, do we know whether we use mono or aave for converting the albedos from ocean to atmos grid?

@mt5555 or others: I don't understand how the 'mono' remap works. I assumed it was monotone and therefore shouldn't create new extrema, but maybe I'm wrong. Or maybe we should never create mono maps from finer to coarser resolution?

**Comment by mt5555** [comment] 2022-05-03 19:35
Running:  ncks --chk_map map_ne120np4_to_r0125_mono.20200508.nc
shows that the weights range from -2.7e-20 to .97388, which is good.  
The row sums do have a slight overshoot:  frac_b max: 1.0000000000261824, which would explain the values you posted above.

Is it clear that these small overshoots are causing the problem?  



On this page: 
https://acme-climate.atlassian.net/wiki/spaces/DOC/pages/178848194/Transition+to+TempestRemap+for+Atmosphere+grids
we recommend the "monotr" map for land->atm fluxes.  I can try producing that map and see if it's row sums are any better.

**Comment by mt5555** [comment] 2022-05-03 20:04
is this a tri-grid configuration?  if the problem is at the ocean/land interface, I'd suspect something in the partial franctions used by the tri-gird.

**Comment by wlin7** [comment] 2022-05-03 20:33
> @wlin7 - could you retry the r0125->ne120 mono map with some entries set to zero instead of 1? My suspicion is that this will make the overshoots worse.
> 
Good thought. I am going to do a test, by randomly assign 0 values. Dont feel the overshoot would be worse, though, because all the pre-computed weights are non-negative.

> Also, do we know whether we use mono or aave for converting the albedos from ocean to atmos grid?

aave map: map_oRRS18to6v3_to_ne120np4_aave.170111.nc. It is the map for ocn2atm and ice2atm, as can be seen in seq_map.rc.

**Comment by wlin7** [comment] 2022-05-03 21:18
A mapping test with source data on r0125, 0 values over ocean and random 20% of land, 1 else where. The remapped data on ne120np4 has no overshooting, but a surprise undershooting with min of  -5.056173995e-23.

**Comment by PeterCaldwell** [comment] 2022-05-03 22:04
Isn't that consistent with the sum of the weights across a column adding up to slightly more than 1?

Also, if we're using aave to regrid albedo, I'm not sure this analysis of mono is relevant?

**Comment by wlin7** [comment] 2022-05-04 02:53
The mono map from land r0125 to ne120 is relevant for the current tri-grid test, as we don't have info to tell if the out-of-bound values are over ocean/ice or land or both.

**Comment by AaronDonahue** [comment] 2024-11-14 19:32
@PeterCaldwell and @wlin7 , is this still an issue with our runs?

**Comment by wlin7** [comment] 2024-12-06 18:19
The puzzle may remain, but we haven't seen it causing issues with our runs. Closed it now.

**Closed by wlin7** 2024-12-06 18:19 UTC
