### ISSUE TITLE
Model crash at ne30 -- T above 500k (likely fixed with macmic=12)

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/scream#2381] opened 2023-06-13 23:41 UTC
My latest simulation with EAMxx at ne30 crashed a little over after one year. I have performed a number of ne30 simulations before, none of which failed. I've verified that the crash is reproducible.

The model fails because of excessively large temperature 514 K) in BC, Canada on April 1

From atm.log

```
Atmosphere step = 21839
  model time = 0002-03-31 23:30:00

[EAMxx::output_manager] - Writing model output:
[EAMxx::output_manager]      CASE: 20230607.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.scream.monthly
[EAMxx::output_manager]      FILE: 20230607.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.scream.monthly.AVERAGE.nmonths_x1.0002-03-01-00000.nc
Atmosphere step = 21840
  model time = 0002-04-01 00:00:00

```

From e3sm.log

```
 858: terminate called after throwing an instance of 'std::logic_error'
 858:   what():  /gpfs/fs1/home/ac.golaz/E3SM/EAMxx/code/20230607/components/eamxx/src/share/atm_process/atmosphere_process.cpp:442: FAIL:
 858: false
 858: Error! Failed post-condition property check (cannot be repaired).
 858:   - Atmosphere process name: shoc
 858:   - Property check name: T_mid within interval [100, 500]
 858:   - Atmosphere process MPI Rank: 858
 858:   - Message: Check failed.
 858:   - check name: T_mid within interval [100, 500]
 858:   - field id: T_mid[Physics PG2] <double:ncol,lev>(12,128) [K]
 858:   - minimum:
 858:     - value: 211.163
 858:     - entry: (20541,60)
 858:     - lat/lon: (56.7783, 238.776)
 858:   - maximum:
 858:     - value: 514.47
 858:     - entry: (20663,127)
 858:     - lat/lon: (54.7812, 232.505)
```

Simulation output is available on chrysalis:
 `/lcrc/group/e3sm/ac.golaz/E3SM/EAMxx/20230607.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis`

Run script is attached: 
[run_20230607.F2010-SCREAMv1.ne30.chrysalis.sh.txt](https://github.com/E3SM-Project/scream/files/11740151/run_20230607.F2010-SCREAMv1.ne30.chrysalis.sh.txt)

**Comment by oksanaguba** [comment] 2023-06-14 03:39
i have been slowly running ne30 v1 128 levels on frontier, it is now in 8th year.

**Comment by ambrad** [comment] 2023-06-14 18:59
What is the PE layout used in this run? I think the default on Chrysalis is 2 threads/rank for testing. I believe there might be a threading issue in SHOC's interface. In any case, if you're not running already with 64x1, I recommend doing so.

**Comment by ndkeen** [comment] 2023-06-14 19:01
These were both 1800x1

**Comment by golaz** [comment] 2023-06-14 19:10
The divergence occurs after time step 17802 (model time = 0002-01-06 21:00:00) and before 17820 (model time = 0002-01-07 06:00:00). So this is during the second year and was reproduced in my rerun starting 0002-01-01.

bfbhash for my simulation (left) and Noel's (right):

![Screenshot_2023-06-14_11-48-20](https://github.com/E3SM-Project/scream/assets/15743046/8cabe828-5a74-44d9-9963-9b211545117e)

**Comment by ambrad** [comment] 2023-06-14 19:15
@ndkeen we're a day or two away from getting the Hommexx diagnostic hasher (just merged to upstream E3SM this morning) into SCREAM to complement the EAMxx diagnostic hasher. These differ from the above hasher in that they emit hashes after every process in the AD and after every boundary exchange in the dycore. I recommend we wait for those to go in, then rerun your setup with instructions that I post to this issue to enable the diagnostic hashers.

**Comment by ndkeen** [comment] 2023-06-15 16:10
I checked out several hashes in between 6/7 and 6/14 and tried the same thing as above.  All of them failed in the same way as described above. That includes using a hash that was the same as the one I had used to see a successful 2-year run. So I ran the same script in the same checkout again -- and it crashes as well.  I went back to at least 5/24 and while I have to change the output as some we were using are new, the code crashes at same 1-year boundary.  Pretty odd.

**Comment by ndkeen** [comment] 2023-06-15 18:51
@gsever it might be better to make a new issue with your specific problem -- include the date of repo and launch script.

**Comment by ndkeen** [comment] 2023-06-15 20:02
The cases I've been running are here:
`/lcrc/group/e3sm/ac.ndkeen/scratch/chrys`

Here are the dirs:
```
drwxr-sr-x   3 ac.ndkeen E3SM    4096 Jun 15 11:02 b2023-04-20-PR2291-82f215a652/
drwxr-sr-x   3 ac.ndkeen E3SM    4096 Jun 15 14:35 b2023-04-24-PR2297-709c430968/
drwxr-sr-x   3 ac.ndkeen E3SM    4096 Jun 15 12:20 b2023-05-04-PR2309-de719afa37/
drwxr-sr-x   3 ac.ndkeen E3SM    4096 Jun 15 13:04 b2023-05-08-PR2321-06a178c79a/
drwxr-sr-x   3 ac.ndkeen E3SM    4096 Jun 14 22:42 b2023-05-24-PR2349-0895d60dbf/
drwxr-sr-x   5 ac.ndkeen E3SM    4096 Jun 15 00:09 b2023-06-01-PR2327-355a4370f1/
drwxr-sr-x   3 ac.ndkeen E3SM    4096 Jun 14 18:23 b2023-06-05-PR2358-d9602e9f16/
drwxr-sr-x   3 ac.ndkeen E3SM    4096 Jun 14 17:04 b2023-06-08-PR2348-4156717c1d/
drwxr-sr-x   3 ac.ndkeen E3SM    4096 Jun 14 18:12 b2023-06-08-PR2365-1084bdc66d/
drwxr-sr-x   3 ac.ndkeen E3SM    4096 Jun 14 17:35 b2023-06-08-PR2367-b88645876a/
drwxr-sr-x   3 ac.ndkeen E3SM    4096 Jun 14 19:18 b2023-06-08-PR2369-6e98c22358/
drwxr-sr-x   3 ac.ndkeen E3SM    4096 Jun 14 17:25 b2023-06-08-PR2371-6273dc31cf/
drwxr-sr-x   3 ac.ndkeen E3SM    4096 Jun 14 18:13 b2023-06-09-PR2370-a38f7a5c99/
drwxr-sr-x   3 ac.ndkeen E3SM    4096 Jun 14 19:59 b2023-06-12-PR2375-afb57c8f82/
drwxr-sr-x   6 ac.ndkeen E3SM    4096 Jun 15 10:59 b2023-06-13-PR2379-5c131ca120/
```

**Comment by ambrad** [comment] 2023-06-15 20:32
Thanks @ndkeen for these runs. Here's a bit of analysis.

I ran
```
(for i in `ls|grep b2023`; do echo ">>> $i"; for j in `find $i -name e3sm.log\*`; do echo ">> $j"; zgrep bfbhash $j; done; done) > ~/tmp/bfb2023.txt
```
and then, once I saw the output,
```
grep ">>> \|>> \|bfbhash>\s*21834\|bfbhash>\s*21654\|bfbhash>\s*17820" bfb2023.txt
```
This procedure gives the following:
```
>>> b2023-04-20-PR2291-82f215a652
>> b2023-04-20-PR2291-82f215a652/t.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.orig/run/e3sm.log.343227.230615-123150.gz
>>> b2023-04-24-PR2297-709c430968
>>> b2023-05-04-PR2309-de719afa37
>> b2023-05-04-PR2309-de719afa37/t.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.orig/run/e3sm.log.343298.230615-131750
>>> b2023-05-08-PR2321-06a178c79a
>> b2023-05-08-PR2321-06a178c79a/t.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.orig/run/e3sm.log.343320.230615-134607
>>> b2023-05-24-PR2349-0895d60dbf
>> b2023-05-24-PR2349-0895d60dbf/t.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.orig.old/run/e3sm.log.342877.230614-232247
   0: bfbhash>          17820 d2cde00a18981e7b (Hommexx)
   0: bfbhash>          21654 3307b987a0346b95 (Hommexx)
   0: bfbhash>          21834 c0a417f93b6c9941 (Hommexx)
>>> b2023-06-01-PR2327-355a4370f1
>> b2023-06-01-PR2327-355a4370f1/t.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.orig/run/e3sm.log.342672.230614-204014
>> b2023-06-01-PR2327-355a4370f1/t.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.orig.old/run/e3sm.log.342951.230615-005246
>>> b2023-06-05-PR2358-d9602e9f16
>> b2023-06-05-PR2358-d9602e9f16/t.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.orig/run/e3sm.log.342668.230614-203845
>>> b2023-06-08-PR2348-4156717c1d
>> b2023-06-08-PR2348-4156717c1d/t.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.orig/run/e3sm.log.342603.230614-180418
   0: bfbhash>          17820 d2cde00a18981e7b (Hommexx)
   0: bfbhash>          21654 3307b987a0346b95 (Hommexx)
   0: bfbhash>          21834 c0a417f93b6c9941 (Hommexx)
>>> b2023-06-08-PR2365-1084bdc66d
>> b2023-06-08-PR2365-1084bdc66d/t.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.orig/run/e3sm.log.342599.230614-163546
   0: bfbhash>          17820 d2cde00a18981e7b (Hommexx)
   0: bfbhash>          21654 3307b987a0346b95 (Hommexx)
   0: bfbhash>          21834 c0a417f93b6c9941 (Hommexx)
>>> b2023-06-08-PR2367-b88645876a
>> b2023-06-08-PR2367-b88645876a/t.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.orig/run/e3sm.log.342633.230614-194215
   0: bfbhash>          17820 d2cde00a18981e7b (Hommexx)
   0: bfbhash>          21654 3307b987a0346b95 (Hommexx)
   0: bfbhash>          21834 c0a417f93b6c9941 (Hommexx)
>>> b2023-06-08-PR2369-6e98c22358
>> b2023-06-08-PR2369-6e98c22358/t.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.orig/run/e3sm.log.342740.230614-204314
   0: bfbhash>          17820 d2cde00a18981e7b (Hommexx)
   0: bfbhash>          21654 3307b987a0346b95 (Hommexx)
   0: bfbhash>          21834 c0a417f93b6c9941 (Hommexx)
>>> b2023-06-08-PR2371-6273dc31cf
>> b2023-06-08-PR2371-6273dc31cf/t.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.orig/run/e3sm.log.342630.230614-190045
   0: bfbhash>          17820 d2cde00a18981e7b (Hommexx)
   0: bfbhash>          21654 3307b987a0346b95 (Hommexx)
   0: bfbhash>          21834 c0a417f93b6c9941 (Hommexx)
>>> b2023-06-09-PR2370-a38f7a5c99
>> b2023-06-09-PR2370-a38f7a5c99/t.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.orig/run/e3sm.log.342595.230614-163244
   0: bfbhash>          17820 d2cde00a18981e7b (Hommexx)
   0: bfbhash>          21654 3307b987a0346b95 (Hommexx)
   0: bfbhash>          21834 c0a417f93b6c9941 (Hommexx)
>>> b2023-06-12-PR2375-afb57c8f82
>> b2023-06-12-PR2375-afb57c8f82/t.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.orig/run/e3sm.log.342607.230614-181045
   0: bfbhash>          17820 d2cde00a18981e7b (Hommexx)
   0: bfbhash>          21654 3307b987a0346b95 (Hommexx)
   0: bfbhash>          21834 c0a417f93b6c9941 (Hommexx)
>>> b2023-06-13-PR2379-5c131ca120
>> b2023-06-13-PR2379-5c131ca120/t.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.orig/run/e3sm.log.342666.230614-194845
   0: bfbhash>          17820 d2cde00a18981e7b (Hommexx)
   0: bfbhash>          21654 3307b987a0346b95 (Hommexx)
   0: bfbhash>          21834 c0a417f93b6c9941 (Hommexx)
>> b2023-06-13-PR2379-5c131ca120/t.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.orig.noyaml/run/e3sm.log.343226.230615-115317
   0: bfbhash>          17820 d2cde00a18981e7b (Hommexx)
   0: bfbhash>          21654 3307b987a0346b95 (Hommexx)
>> b2023-06-13-PR2379-5c131ca120/t.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.origb/run/e3sm.log.342913.230615-001146
   0: bfbhash>          17820 d2cde00a18981e7b (Hommexx)
   0: bfbhash>          21654 3307b987a0346b95 (Hommexx)
   0: bfbhash>          21834 c0a417f93b6c9941 (Hommexx)
>> b2023-06-13-PR2379-5c131ca120/t.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.origc/run/e3sm.log.343198.230615-111819
   0: bfbhash>          17820 d2cde00a18981e7b (Hommexx)
   0: bfbhash>          21654 3307b987a0346b95 (Hommexx)
   0: bfbhash>          21834 c0a417f93b6c9941 (Hommexx)
```
We see the following:
- Every run that Noel has in these directories agrees at 17820 with Chris's run.
- Every run agrees at 21834, right before the crash.

The preliminary conclusion is that the repo has for very roughly one to three months reliably reproduced the crash Chris reported. It seems the outlier is the run that Noel reports above in `/lcrc/group/e3sm/ac.ndkeen/scratch/chrys/s12-jun14/t.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.orig`, which diffs with Chris's run and the b2023 runs at time step 17820.

**Comment by ndkeen** [comment] 2023-06-16 00:47
I can reproduce the crash on pm-cpu with intel.

**Comment by ambrad** [comment] 2023-06-16 01:36
The wet-dry change certainly modified answers, so the PR Noel isolated makes sense.

**Comment by oksanaguba** [comment] 2023-06-16 01:43
i am not following this thread and it may not be relevant, but wet-dry had a bug in geopotential in p3 (found by Peter B.), so it would lead to unphysical tendencies.

**Comment by ndkeen** [comment] 2023-06-16 01:57
Maybe
 `81a9193ed8 2023-06-06 05:56:54 -0700 AaronDonahue       Merge pull request #2356 from E3SM-Project/bogensch/p3_dz_fix`

**Comment by ambrad** [comment] 2023-06-16 02:35
No, p3_dz_fix is for F90 only.

**Comment by ambrad** [comment] 2023-06-16 02:36
> i am not following this thread and it may not be relevant, but wet-dry had a bug in geopotential in p3 (found by Peter B.), so it would lead to unphysical tendencies.

Just to be clear, the issue arises after, not before, this PR. Not saying the PR has a bug, just clarifying.

**Comment by ndkeen** [comment] 2023-06-18 03:04
I verified that I see the same issue on pm-cpu with intel -- ie a run using hash before the commit noted above runs OK, but with
`270f4efc76 2023-05-10 09:44:15 -0700 AaronDonahue       Merge pull request #2193 from E3SM-Project/oksanaguba/eamxx/wetdry`
it crashes with high T.

```
case with repo before PR 2193 (runs to at least model date =   00020928)
/pscratch/sd/n/ndk/e3sm_scratch/pm-cpu/b2023-05-08-PR2321-06a178c79a/t.intel.F2010-SCREAMv1.ne30pg2_ne30pg2.pm-cpu.n015

and case with PR 2193: (crashes at model date =   00010212)
/pscratch/sd/n/ndk/e3sm_scratch/pm-cpu/b2023-05-10-PR2193-270f4efc76/t.intel.F2010-SCREAMv1.ne30pg2_ne30pg2.pm-cpu.n015
```

**Comment by ndkeen** [comment] 2023-06-22 18:01
Peter C had suggested we get a restart closer to the crash, increase the level output, and run again. On pm-cpu, it crashes fairly quickly, but I did get a restart after 1 month here:

`/pscratch/sd/n/ndk/e3sm_scratch/pm-cpu/se68-jun15/t.F2010-SCREAMv1.ne30pg2_ne30pg2.pm-cpu.orig`

I just don't know what set of outputs to use that would be helpful.

**Comment by ndkeen** [comment] 2023-06-22 21:33
I noted above regarding finer output. I also wanted to note that changing the PE layout seems to be causing the case to behave differently.  The original case on chrysalis reported by Chris G was 1800x1.  On pm-cpu, I've been repeating that 1800x1 configuration which is using 15 nodes (at 128 MPI's per node).

Running with 8 nodes allowed me to run at least 2 years without issue on pm-cpu:
`/pscratch/sd/n/ndk/e3sm_scratch/pm-cpu/se68-jun15/t.F2010-SCREAMv1.ne30pg2_ne30pg2.pm-cpu.n008`

And then running on frontier, I have run quite a while without issues. I will try specifically 1800x1.

**Comment by ambrad** [comment] 2023-06-23 01:53
Since you're now seeing what seems to be PE-layout-related non-BFBness, you could use the diagnostic-level hashing to determine the culprit:
```
atmchange --all internal_diagnostics_level=1 atmosphere_processes::internal_diagnostics_level=0
```
This line will produce a large number of `hxxhash>` lines (for Hommexx internals) in addition to `exxhash>` (for EAMxx AD processes) lines. In case you want to disable the Hommexx hashing, add an additional argument to the above to disable it:
```
./atmchange --all internal_diagnostics_level=1 atmosphere_processes::internal_diagnostics_level=0 ctl_nl::internal_diagnostics_level=0
```
In any case, you can grep an e3sm.log file with `exxhash` to get AD lines only, `hxxhash` for Homme only, or `xxhash` to get them all.

**Comment by ndkeen** [comment] 2023-06-23 02:54
Hmm, OK.  I launched 3 tests on pm-cpu for 2 months each:

```
1024 MPIs
/pscratch/sd/n/ndk/e3sm_scratch/pm-cpu/se68-jun15/t.intel.F2010-SCREAMv1.ne30pg2_ne30pg2.pm-cpu.n008.od.idl0

1800 MPIs
/pscratch/sd/n/ndk/e3sm_scratch/pm-cpu/se68-jun15/t.intel.F2010-SCREAMv1.ne30pg2_ne30pg2.pm-cpu.n015.od.idl0

2700 MPIs
/pscratch/sd/n/ndk/e3sm_scratch/pm-cpu/se68-jun15/t.intel.F2010-SCREAMv1.ne30pg2_ne30pg2.pm-cpu.n022.od.idl0
```

**Comment by ndkeen** [comment] 2023-06-23 18:01
As the scream checkout from yesterday is not crashing the same way as it did with June15th repo, I'm running the same 15-node 1800x1 case longer (without additional hash info). It's currently almost a year into simulation.
`/pscratch/sd/n/ndk/e3sm_scratch/pm-cpu/se69-jun22/t.intel.F2010-SCREAMv1.ne30pg2_ne30pg2.pm-cpu.n015.od`
I think on chrysalis, this case failed closer to 2 years in. Both of these are with Intel.

Note that scream repo must not have been upstream merged in a while as I don't have the Intel compiler changes in there and made them locally.

**Comment by ambrad** [comment] 2023-06-23 19:19
The hxxhash lines are the problem in the beginning, but what you show is just the exxhash lines. Thus, the flagged line is a valid diff, isolated to the Hommexx AD process. We see the diff propagate subsequently to all the exxhash lines. But in this case it may not be Hommexx in particular, since this is all happening immediately after init. I wonder if there is PE-layout dependence in the initialization phase that our nightly ERP/PEM tests aren't capturing.

**Comment by ndkeen** [comment] 2023-06-23 20:33
Just quickly, using cprnc on two `cpl.hi` files in 8-node and 22-node dirs, it does indicate differences.  So we may have 2 issues here: non-bfb with different PE layout tests (should be caught with PEM test) *and* a crash with too high T for at least one PE layout.

**Comment by ambrad** [comment] 2023-06-23 22:44
Runs on Chrysalis show no diffs. Perhaps this is an issue isolated to pm-cpu Intel.

Script:
```bash
tests=""
for npe in 256 362 512 640; do   
    for compiler in gnu intel; do
        tests+=" PEM_P${npe}x1_Ld1.ne30pg2_ne30pg2.F2010-SCREAMv1.chrysalis_${compiler}"
    done
done
$e3sm/cime/scripts/create_test $tests --machine chrysalis --project $wcid -j 64
```

Results showing both `PASS` for each test and `bfbhash` comparison among tests:
```
$ ./cs.status.20230623_164037_6v0xpu | grep Overall; for compiler in gnu intel; do echo $compiler; for i in PEM_*${compiler}*; do zgrep bfbhash $i/run/e3sm.log* | tail -n 1; done; done
  PEM_P256x1_Ld1.ne30pg2_ne30pg2.F2010-SCREAMv1.chrysalis_gnu (Overall: PASS) details:
  PEM_P256x1_Ld1.ne30pg2_ne30pg2.F2010-SCREAMv1.chrysalis_intel (Overall: PASS) details:
  PEM_P362x1_Ld1.ne30pg2_ne30pg2.F2010-SCREAMv1.chrysalis_gnu (Overall: PASS) details:
  PEM_P362x1_Ld1.ne30pg2_ne30pg2.F2010-SCREAMv1.chrysalis_intel (Overall: PASS) details:
  PEM_P512x1_Ld1.ne30pg2_ne30pg2.F2010-SCREAMv1.chrysalis_gnu (Overall: PASS) details:
  PEM_P512x1_Ld1.ne30pg2_ne30pg2.F2010-SCREAMv1.chrysalis_intel (Overall: PASS) details:
  PEM_P640x1_Ld1.ne30pg2_ne30pg2.F2010-SCREAMv1.chrysalis_gnu (Overall: PASS) details:
  PEM_P640x1_Ld1.ne30pg2_ne30pg2.F2010-SCREAMv1.chrysalis_intel (Overall: PASS) details:
gnu
  0: bfbhash>             36 d228e1e60be6efd2 (Hommexx)
  0: bfbhash>             36 d228e1e60be6efd2 (Hommexx)
  0: bfbhash>             36 d228e1e60be6efd2 (Hommexx)
  0: bfbhash>             36 d228e1e60be6efd2 (Hommexx)
intel
  0: bfbhash>             36 ed625355c8369ff8 (Hommexx)
  0: bfbhash>             36 ed625355c8369ff8 (Hommexx)
  0: bfbhash>             36 ed625355c8369ff8 (Hommexx)
  0: bfbhash>             36 ed625355c8369ff8 (Hommexx)
```

**Comment by ndkeen** [comment] 2023-06-29 21:07
I verified that I get the same crash (T above 500k) on chrysalis if I run with a diff PE layout (2700x1 instead of the above 1800x1). I also see the same hash values in e3sm log.
`/lcrc/group/e3sm/ac.ndkeen/scratch/chrys/s12-jun14/t.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.p2700x1`

**Comment by ambrad** [comment] 2023-06-30 00:27
@ndkeen is it fair to summarize things as follows?
1. The model crash with T>500K is legitimate.
2. Chrysalis has no evident non-BFBness.
3. In the course of investigating this issue, it was observed that pm-cpu/ifx has non-BFBness, Frontier had non-BFBness that is now (probably) resolved, and neither of these -- since they are very likely related to platform-specific compilers -- is relevant to this issue.

**Comment by ndkeen** [comment] 2023-06-30 02:31
Note that pm-cpu/intel is actually using 
```
login40% ftn --version
ifort (IFORT) 2021.9.0 20230302
```

I decided to also run the same case with GNU on chyrsalis. Surprisingly, that also failed with high T.
At `model date =   00020423`, which is about 22 days beyond where it happens with Intel on this machine.
`/lcrc/group/e3sm/ac.ndkeen/scratch/chrys/s12-jun14/t.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.p2700x1.gnu`

None of the other longer-running tests on pm-cpu or frontier have had issues.

I'm now running the same case with increased output.

**Comment by crterai** [comment] 2023-06-30 18:17
I took a look at the output and the e3sm log. The crash 'report' in e3sm log file was quite helpful and based on it,
```
1287:  -----------------------------------------------------------------------
1287:      surf_sens_flux<ncol>(8)
1287:
1287:   surf_sens_flux(2)
1287:     4679.2,
```
This value of 4679 Wm-2 is quite high (especially given that max solar flux is 1373 Wm-2), so something is going awry at the surface to be getting that high. 
Looking at the temperature tendency output that Noel shared above, the maximum temperature tendency comes from SHOC (not surprisingly), and shows the following tendency in the column that shows maximum temperature tendency. It's consistent with a high surface sensible heat flux.
![image](https://github.com/E3SM-Project/scream/assets/12244479/19d30d83-5e97-4360-bade-226d8c0a3d96)

**Comment by ndkeen** [comment] 2023-06-30 18:55
I might have found the issue.  Or at least something quite troubling.  The script I was given from Chris G had the following: ```
elif [ "${MACHINE}" == "chrysalis" ]; then

    # Activate conda environment for building                                                                                                                                                                   
    source /lcrc/soft/climate/e3sm-unified/load_latest_e3sm_unified_chrysalis.sh                                                                                                                               
```
that is, use e3sm unified env for chrysalis -- but a) I've never heard of this being something we would want to do for e3sm sims and b) I did not use this for runs on other machines.

I'm trying a test now without the conda env, and sure enough, the hashes are different right away.

**Comment by ndkeen** [comment] 2023-07-06 01:04
I tried a few more experiments on chrysalis, including one where I changed the floating-point model for the intel compiler. Currently, this machine uses precise or source, but if I add the even-more-safe `-fp-model consistent` to both fortran and C++ builds, the case will complete 2 years (ie not crash).

**Comment by ndkeen** [comment] 2023-07-21 21:02
Using July20th scream repo, I first tried the same 2700x1 case again to verify it fails in same way (it does).
`/lcrc/group/e3sm/ac.ndkeen/scratch/chrys/s13-jul20/t.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.p2700x1`

And then I made the change to add the consistent flag to CXX builds and ran 5 years. It completed here:
`/lcrc/group/e3sm/ac.ndkeen/scratch/chrys/s13-jul20/t.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.p2700x1.cxxfpcons`

Can we see if the output written here is enough to verify it's OK?  What's next step?

**Comment by ndkeen** [comment] 2023-07-22 19:49
For the case that completed 5 years, I ran another 5 years.
And then tried to run longer. It does then crash around model date `0014-12-01` with:

```
1219: terminate called after throwing an instance of 'std::logic_error'
1219:   what():  /lcrc/group/e3sm/ac.ndkeen/wacmy/s13-jul20/components/eamxx/src/share/atm_process/atmosphere_process.cpp:442: FAIL:
1219: false
1219: Error! Failed post-condition property check (cannot be repaired).
1219:   - Atmosphere process name: shoc
1219:   - Property check name: T_mid within interval [100, 500]
1219:   - Atmosphere process MPI Rank: 1219
1219:   - Message: Check failed.
1219:   - check name: T_mid within interval [100, 500]
1219:   - field id: T_mid[Physics PG2] <double:ncol,lev>(8,128) [K]
1219:   - minimum:
1219:     - value: 209.438
1219:     - entry: (18974,13)
1219:     - lat/lon: (52.6446, 298.907)
1219:   - maximum:
1219:     - value: 513.967
1219:     - entry: (18971,127)
1219:     - lat/lon: (49.3578, 293.3)

/lcrc/group/e3sm/ac.ndkeen/scratch/chrys/s13-jul20/t.F2010-SCREAMv1.ne30pg2_ne30pg2.chrysalis.p2700x1.cxxfpcons
```

**Comment by ndkeen** [comment] 2023-07-24 15:41
I then wanted to try this case on perlmutter for much longer (previously had only ran about 2 years). For pm-gpu and pm-cpu, I started cases -- both using GNU compiler.  They both failed with same error.

pm-cpu fails at `00060108`
```
1222:   what():  /global/cfs/cdirs/e3sm/ndk/repos/se70-jul19/components/eamxx/src/share/atm_process/atmosphere_process.cpp:442: FAIL:
1222: false
1222: Error! Failed post-condition property check (cannot be repaired).
1222:   - Atmosphere process name: shoc
1222:   - Property check name: T_mid within interval [100, 500]
1222:   - Atmosphere process MPI Rank: 1222
1222:   - Message: Check failed.
1222:   - check name: T_mid within interval [100, 500]
1222:   - field id: T_mid[Physics PG2] <double:ncol,lev>(8,128) [K]
1222:   - minimum:
1222:     - value: 212.477
1222:     - entry: (18738,8)
1222:     - lat/lon: (52.3016, 309.656)
1222:   - maximum:
1222:     - value: 500.44
1222:     - entry: (18857,127)
1222:     - lat/lon: (52.6412, 304.254)
```

pm-gpu fails at `00060102`
```
28:   what():  /global/cfs/cdirs/e3sm/ndk/repos/se70-jul19/components/eamxx/src/share/atm_process/atmosphere_process.cpp:442: FAIL:
28: false
28: Error! Failed post-condition property check (cannot be repaired).
28:   - Atmosphere process name: shoc
28:   - Property check name: T_mid within interval [100, 500]
28:   - Atmosphere process MPI Rank: 28
28:   - Message: Check failed.
28:   - check name: T_mid within interval [100, 500]
28:   - field id: T_mid[Physics PG2] <double:ncol,lev>(336,128) [K]
28:   - minimum:
28:     - value: 191.035
28:     - entry: (18888,14)
28:     - lat/lon: (66.5198, 336.697)
28:   - maximum:
28:     - value: 527.788
28:     - entry: (18852,127)
28:     - lat/lon: (49.7449, 298.117)
```

**Comment by crterai** [comment] 2023-07-26 18:02
In `/pscratch/sd/n/ndk/e3sm_scratch/pm-cpu/se70-jul19/t.gnu.F2010-SCREAMv1.ne30pg2_ne30pg2.pm-cpu.n022.om`
the sensible heat flux is again really high: 
```
1222:      surf_sens_flux<ncol>(8)
1222:
1222:   surf_sens_flux(4)
1222:     4780.03,
```
And in `/pscratch/sd/n/ndk/e3sm_scratch/pm-gpu/se70-jul19/t.gnugpu.F2010-SCREAMv1.ne30pg2_ne30pg2.pm-gpu.n016.om` the sensible heat flux is:
```
28:  -----------------------------------------------------------------------
28:      surf_sens_flux<ncol>(336)
28:
28:   surf_sens_flux(203)
28:     5524.88,
28:  -----------------------------------------------------------------------
```

**Comment by crterai** [comment] 2023-07-28 22:27
I did some analysis on the pm-gpu case, where Noel ran with timestep level output at the surface. I was expecting to see these very large sensible heat flux (SHF) values to be coming from a warming up surface, but there's no indication of this occurring - which is quite surprising. Apart from some numerical issue, I can't think of a physical explanation for why these large SHF values, which in turn warm up the bottom layer, occur. 

First, I looked at the global maximum SHF values every timestep to see how large they got. 
![image](https://github.com/E3SM-Project/scream/assets/12244479/4cb27bae-369e-4514-945f-7cb75b13780a)
There were a few cases, where the SHF got higher than 1700 Wm-2. For context, the solar constant is ~1300 Wm-2. 
I mapped out where these cases occurred and found that they occur over land (this is consistent with where all of the hot T crashes have occurred). 
![image](https://github.com/E3SM-Project/scream/assets/12244479/643da33b-f202-4031-840c-d94fb774e049)
I was also curious to see if the surface radiative temperature is really high where the SHF gets to be really high for these high SHF cases. But I found that in many cases, the atmosphere was warmer than the surface. 
![image](https://github.com/E3SM-Project/scream/assets/12244479/be50b7ac-2f99-4d06-88af-e79abda218b2)
Finally, I looked at the time evolution of sensible heat flux, downward SW radiation at the surface, surface T (`surf_radiative_T`), and T_mid at the bottom level (`T_mid_at_model_bot`) to see what happens, and the high SHF seems to just occur out of no-where and be quite localized. 
https://portal.nersc.gov/cfs/e3sm/terai/SCREAM/v1_analysis/ne30_HotT_analysis/SCREAMv1_ne30_HotT_caseA.gif

Very odd...

**Comment by ndkeen** [comment] 2023-08-08 20:22
I'm seeing hangs with my runs on pm-gpu.  I see them around `model date =   00070103` and I've tried about 6 cases now.  Some cases restart, others run straight thru.

**Comment by ndkeen** [comment] 2023-09-07 17:16
After much testing, @bogensch suggested that we use macmic=12 (current default is 6) as this matches the original formulation. When I ran a ne30 case (on pm-gpu) with macmic=12, it ran for at least 115 years. We think this should only affect ne30 runs (?)

I was going to make a PR from this branch:
`ndk/scream/set-ne30-macmic-12`

**Comment by AaronDonahue** [comment] 2023-09-07 17:53
Just to make sure, we basically want the shoc timestep to be <= 150s.  What is the default ATM timestep for ne120, ne256, ne512?  We can then compare against default mac_aero_mic subcycling in EAMxx and capture these cases in your PR too @ndkeen .

**Comment by PeterCaldwell** [comment] 2023-09-07 17:57
ne120 has a 5 min SHOC dt so needs this treatment as well. Not sure about ne256 or ne512.

**Comment by ndkeen** [comment] 2023-09-07 23:33
I would think we would want to make this change to default ne30 to fix the issue that we know is there. If we want to change other defaults, can make another GH issue as it will likely take testing.

**Comment by PeterCaldwell** [comment] 2023-09-07 23:36
We might as well change both ne30 and ne120 defaults since we know they are both wrong. Can you make this PR, Noel? I think we're all in agreement we need to do it, but everyone's hair is on fire and I don't know how to fix it myself...

**Comment by bartgol** [comment] 2023-09-07 23:43
Right now, `dt_atm` is not passed to the atm procs at init time. However, we may change that, so that procs can pre-compute some dt-related quantities. In particular, shoc could do
```
m_num_subcycles = static_cast<int>(std::ceil ( atm_dt / shoc_dt_max ) );
```

I didn't make dt available at init time, since I didn't consider it an init-time parameter. But eam does it, and I don't foresee the coupler implementing time-adaptivity anyways, so we can assume dt is written in stone right from the start, and we may as well use it...

**Comment by PeterCaldwell** [comment] 2023-09-08 00:02
I'm kinda creeped out by the idea that the code would silently change the timestep it is using (or even declare that it's changing things in a log file nobody will read). I'd rather it did what the user asked for even if it was dumb. I like how homme gets around this by having the user specify all the timesteps they want to use rather than the number of substeps to take for certain things. 

In this case, though, I think we should just change the default number of substeps for macro and micro for ne30 and ne120 and move on. We might need to have a further PR for ne256 and ne512, but we can do so if/when we encounter a problem (which I doubt we will).

**Closed** 2023-09-13 16:10 UTC
